import { Album } from '../types/Album';

export const fetchAlbums = async (): Promise<Album[]> => [
  {
    id: '1',
    title: 'Guitar Hero I',
    coverImage: "./images/guitarheroi2.png",
    platform: 'PlayStation 2',
    releaseDate: '08/11/2005',
    description: 'O primeiro Guitar Hero.',
    tracks: [
      { number: 1, title: 'I Love Rock And Roll', artist: 'Joan Jett', ano: '1982', versao: 'Guitar Hero I' },
      { number: 2, title: 'I Wanna Be Sedated', artist: 'The Ramones', ano: '1978', versao: 'Guitar Hero I' },
      { number: 3, title: 'Thunderkiss 65', artist: 'White Zombie', ano: '1978', versao: 'Guitar Hero I' },
      { number: 4, title: 'Smoke On The Water', artist: 'Deep Purple', ano: '1973', versao: 'Guitar Hero I' },
      { number: 5, title: 'Infected', artist: 'Bad Religion', ano: '1994', versao: 'Guitar Hero I' },
      { number: 6, title: 'Iron Man', artist: 'Black Sabbath', ano: '1970', versao: 'Guitar Hero I' },
      { number: 7, title: 'More Than A Feeling', artist: 'Boston', ano: '1976', versao: 'Guitar Hero I' },
      { number: 8, title: 'You Got Another Thing Comin', artist: 'Judas Priest', ano: '1992', versao: 'Guitar Hero I' },
      { number: 9, title: 'Take Me Out', artist: 'Franz Ferdnand', ano: '2004', versao: 'Guitar Hero I' },
      { number: 10, title: 'Sharp Dressed Man', artist: 'ZZ Top', ano: '1993', versao: 'Guitar Hero I' },
      { number: 11, title: 'Killer Queen', artist: 'Queen', ano: '1974', versao: 'Guitar Hero I' },
      { number: 12, title: 'Hey You', artist: 'The Exies', ano: '2004', versao: 'Guitar Hero I' },
      { number: 13, title: 'Stellar', artist: 'Incubus', ano: '1991', versao: 'Guitar Hero I' },
      { number: 14, title: 'Heart Full of Black', artist: 'Burning Brides', ano: '2004', versao: 'Guitar Hero I' },
      { number: 15, title: 'Symphony Of Destruction', artist: 'Megadeth', ano: '1992', versao: 'Guitar Hero I' },
      { number: 16, title: 'Zigg Stardut', artist: 'David Bowie', ano: '1972', versao: 'Guitar Hero I' },
      { number: 17, title: 'Fat Lip', artist: 'Sum 41', ano: '2001', versao: 'Guitar Hero I' },
      { number: 18, title: 'Cochise', artist: 'Audioslave', ano: '2002', versao: 'Guitar Hero I' },
      { number: 19, title: 'Take It Off', artist: 'The Donnas', ano: '2002', versao: 'Guitar Hero I' },
      { number: 20, title: 'Unsung', artist: 'Helmet', ano: '1992', versao: 'Guitar Hero I' },
      { number: 21, title: 'Spanish Castle Magic', artist: 'Jimi Hendrix', ano: '1967', versao: 'Guitar Hero I' },
      { number: 22, title: 'Higher Ground', artist: 'Red Hot Chili Peppers', ano: '1989', versao: 'Guitar Hero I' },
      { number: 23, title: 'No One Knows', artist: 'Queens Of The Stone Age', ano: '2002', versao: 'Guitar Hero I' },
      { number: 24, title: 'Ace Of Spades', artist: 'Motorhead', ano: '1980', versao: 'Guitar Hero I' },
      { number: 25, title: 'Crossroads', artist: 'Cream', ano: '1968', versao: 'Guitar Hero I' },
      { number: 26, title: 'Godzila', artist: 'Blue Oyster Cult', ano: '1977', versao: 'Guitar Hero I' },
      { number: 27, title: 'Texas Flood', artist: 'Stevie Ray Vaugun', ano: '1983', versao: 'Guitar Hero I' },
      { number: 28, title: 'Frankenstein', artist: 'Edgar Winter Group', ano: '1972', versao: 'Guitar Hero I' },
      { number: 29, title: 'Cowboys From Hell', artist: 'Pantera', ano: '1990', versao: 'Guitar Hero I' },
      { number: 30, title: 'Bark At The Moon', artist: 'Ozzy Osbourne', ano: '1983', versao: 'Guitar Hero I' },
      { number: 31, title: 'Fire It Up', artist: 'Black Label Society', ano: '2005', versao: 'Guitar Hero I' },
      { number: 32, title: 'Cheat On The Church', artist: 'Graveyard BBQ', ano: '2005', versao: 'Guitar Hero I' },
      { number: 33, title: 'Caveman Re Joice', artist: 'The Bags', ano: '2005', versao: 'Guitar Hero I' },
      { number: 34, title: 'Eureka! I Found Love', artist: 'The Upper Crust', ano: '2001', versao: 'Guitar Hero I' },
      { number: 35, title: 'All of This', artist: 'Shaimus', ano: '2005', versao: 'Guitar Hero I' },
      { number: 36, title: 'Behind The Mask', artist: 'Anarchy Club', ano: '2005', versao: 'Guitar Hero I' },
      { number: 37, title: 'The Break Wheel', artist: 'Artillery', ano: '2005', versao: 'Guitar Hero I' },
      { number: 38, title: 'Call Out', artist: 'The Agro-Breats', ano: '2005', versao: 'Guitar Hero I' },
      { number: 39, title: 'Decontrol', artist: 'Drist', ano: '2005', versao: 'Guitar Hero I' },
      { number: 40, title: 'Even Rats', artist: 'The Slip', ano: '2006', versao: 'Guitar Hero I' },
      { number: 41, title: 'Farewell Myth', artist: 'Made In Mexico', ano: '2005', versao: 'Guitar Hero I' },
      { number: 42, title: 'Fly On The Wall', artist: 'Din', ano: '2005', versao: 'Guitar Hero I' },
      { number: 43, title: 'Get Ready 2 Rock', artist: 'Freezepop', ano: '2000', versao: 'Guitar Hero I' },
      { number: 44, title: 'Theme From Guitar Hero', artist: 'Monkey Steal The Peach', ano: '2005', versao: 'Guitar Hero I' },
      { number: 45, title: 'Hey', artist: 'Honest Bob And The Factory To Dealer Incentives', ano: '2004', versao: 'Guitar Hero I' },
      { number: 46, title: 'Sail Your Ship By', artist: 'Countzero', ano: '2005', versao: 'Guitar Hero I' },
      { number: 47, title: 'The Story Of My Love', artist: 'The Model Sons', ano: '2005', versao: 'Guitar Hero I' },
      { number: 48, title: 'Trippolette', artist: 'Andrew Buch', ano: '2005', versao: 'Guitar Hero I' },
      { number: 49, title: 'Graveyard Shift', artist: 'Windtunnel Syndrome', ano: '2005', versao: 'Guitar Hero I' }
    ]
  },
  {
    id: '2',
    title: 'Guitar Hero II',
    coverImage: "./images/guitarheroii2.png",
    platform: 'PlayStation 2',
    releaseDate: '07/11/2006',
    description: 'O segundo Guitar Hero.',
    tracks: [
      { number: 1, title: 'Surrender', artist: 'Cheap Trick', ano: '1978', versao: 'Guitar Hero II' },
      { number: 2, title: 'Possum Kingdom', artist: 'Toadies', ano: '1994', versao: 'Guitar Hero II' },
      { number: 3, title: 'Heart-Shaped Box', artist: 'Nirvana', ano: '1993', versao: 'Guitar Hero II' },
      { number: 4, title: 'Salvation', artist: 'Rancid', ano: '1995', versao: 'Guitar Hero II' },
      { number: 5, title: 'Strutter', artist: 'Kiss', ano: '1974', versao: 'Guitar Hero II' },
      { number: 6, title: 'Shout At The Devil', artist: 'Motley Crue', ano: '1983', versao: 'Guitar Hero II' },
      { number: 7, title: 'Mother', artist: 'Danzig', ano: '1988', versao: 'Guitar Hero II' },
      { number: 8, title: 'Life Wasted', artist: 'Pearl Jam', ano: '2006', versao: 'Guitar Hero II' },
      { number: 9, title: 'Cherry Die', artist: 'Warrant', ano: '1990', versao: 'Guitar Hero II' },
      { number: 10, title: 'Woman', artist: 'Wolfmother', ano: '2006', versao: 'Guitar Hero II' },
      { number: 11, title: 'You Really Got Me', artist: 'Van Halen', ano: '1978', versao: 'Guitar Hero II' },
      { number: 12, title: 'Tonight I\'m Gonna Rock You Tonight', artist: 'Spinal Tap', ano: '1984', versao: 'Guitar Hero II' },
      { number: 13, title: 'Carry On Wayward Son', artist: 'Kansas', ano: '1976', versao: 'Guitar Hero II' },
      { number: 14, title: 'Search And Destroy', artist: 'Iggy Pop And The Stooges', ano: '1973', versao: 'Guitar Hero II' },
      { number: 15, title: 'Message In A Bottle', artist: 'The Police', ano: '1979', versao: 'Guitar Hero II' },
      { number: 16, title: 'Billion Dollar Babies', artist: 'Alice Cooper', ano: '1973', versao: 'Guitar Hero II' },
      { number: 17, title: 'Them Bones', artist: 'Alice In Chains', ano: '1992', versao: 'Guitar Hero II' },
      { number: 18, title: 'War Pigs', artist: 'Black Sabbath', ano: '1970', versao: 'Guitar Hero II' },
      { number: 19, title: 'Monkey Wrench', artist: 'Foo Fighters', ano: '1997', versao: 'Guitar Hero II' },
      { number: 20, title: 'Hush', artist: 'Deep Purple', ano: '1967', versao: 'Guitar Hero II' },
      { number: 21, title: 'Girlfriend', artist: 'Matthew Sweet', ano: '1990', versao: 'Guitar Hero II' },
      { number: 22, title: 'Who Was In My Room Last NightP', artist: 'Butthole Surfers', ano: '1993', versao: 'Guitar Hero II' },
      { number: 23, title: 'Can\'t You Hear Me Knocking', artist: 'The Rolling Stones', ano: '1971', versao: 'Guitar Hero II' },
      { number: 24, title: 'Sweet Child O\' Mine', artist: 'Guns N\' Roses', ano: '1988', versao: 'Guitar Hero II' },
      { number: 25, title: 'Rock And Roll, Hoochie Koo', artist: 'Johnny Winter', ano: '1970', versao: 'Guitar Hero II' },
      { number: 26, title: 'Tattooed Love Boys', artist: 'The Pretenders', ano: '1980', versao: 'Guitar Hero II' },
      { number: 27, title: 'John The Fisherman', artist: 'Primus', ano: '1990', versao: 'Guitar Hero II' },
      { number: 28, title: 'Jessica', artist: 'The Allman Brothers Band', ano: '1973', versao: 'Guitar Hero II' },
      { number: 29, title: 'Bad Reputation', artist: 'Thin Lizzy', ano: '1977', versao: 'Guitar Hero II' },
      { number: 30, title: 'Last Child', artist: 'Aerosmith', ano: '1976', versao: 'Guitar Hero II' },
      { number: 31, title: 'Crazy On You', artist: 'Heart', ano: '1976', versao: 'Guitar Hero II' },
      { number: 32, title: 'Trippin\' On A Hole In a Paper Heart', artist: 'Stone Temple Pilots', ano: '1996', versao: 'Guitar Hero II' },
      { number: 33, title: 'Dead!', artist: 'My Chemical Romance', ano: '2006', versao: 'Guitar Hero II' },
      { number: 34, title: 'Killing In The Name', artist: 'Reage Against The Machine', ano: '1993', versao: 'Guitar Hero II' },
      { number: 35, title: 'Freya', artist: 'The Sword', ano: '2006', versao: 'Guitar Hero II' },
      { number: 36, title: 'Stop!', artist: 'Jane\'s Addiction', ano: '1990', versao: 'Guitar Hero II' },
      { number: 37, title: 'Madhouse', artist: 'Anthrax', ano: '1985', versao: 'Guitar Hero II' },
      { number: 38, title: 'The Trooper', artist: 'Iron Maiden', ano: '1983', versao: 'Guitar Hero II' },
      { number: 39, title: 'Rock This Town', artist: 'Stray Cats', ano: '1982', versao: 'Guitar Hero II' },
      { number: 40, title: 'Laid To Rest', artist: 'Lamb Of God', ano: '2004', versao: 'Guitar Hero II' },
      { number: 41, title: 'Psychobilly Freakout', artist: 'The Reverend Horton Heat', ano: '1990', versao: 'Guitar Hero II' },
      { number: 42, title: 'YYZ', artist: 'Rush', ano: '1981', versao: 'Guitar Hero II' },
      { number: 43, title: 'Beast And The Harlot', artist: 'Avanged Sevenfold', ano: '2006', versao: 'Guitar Hero II' },
      { number: 44, title: 'Carry Me Home', artist: 'The Living End', ano: '2000', versao: 'Guitar Hero II' },
      { number: 45, title: 'Institutionalized', artist: 'Suicidal Tendencies', ano: '1983', versao: 'Guitar Hero II' },
      { number: 46, title: 'Misirlou', artist: 'Dick Dale', ano: '1962', versao: 'Guitar Hero II' },
      { number: 47, title: 'Hangar 18', artist: 'Megadeth', ano: '1990', versao: 'Guitar Hero II' },
      { number: 48, title: 'Free Bird', artist: 'Lynyrd Skynyrd', ano: '1973', versao: 'Guitar Hero II' },
      { number: 49, title: 'Raw Dog', artist: 'The Last Vegas', ano: '2006', versao: 'Guitar Hero II' },
      { number: 50, title: 'Arterial Black', artist: 'Drist', ano: '2006', versao: 'Guitar Hero II' },
      { number: 51, title: 'Collide', artist: 'Anarchy Club', ano: '2006', versao: 'Guitar Hero II' },
      { number: 52, title: 'Drink Up', artist: 'Ounce Of Self', ano: '2006', versao: 'Guitar Hero II' },
      { number: 53, title: 'Elephant Bones', artist: 'That HandSome Devil', ano: '2005', versao: 'Guitar Hero II' },
      { number: 54, title: 'Fall Of Pangea', artist: 'Valiente Thorr', ano: '2006', versao: 'Guitar Hero II' },
      { number: 55, title: 'FTK', artist: 'Vagiant', ano: '2006', versao: 'Guitar Hero II' },
      { number: 56, title: 'Gemini', artist: 'Brian Kahanek', ano: '2004', versao: 'Guitar Hero II' },
      { number: 57, title: 'Kicked To The Curb', artist: 'Noble Rot', ano: '2006', versao: 'Guitar Hero II' },
      { number: 58, title: 'Push Push (Lady Lightning)', artist: 'Bang Camaro', ano: '2007', versao: 'Guitar Hero II' },
      { number: 59, title: 'Laughtrack', artist: 'The Agro-Brats', ano: '2005', versao: 'Guitar Hero II' },
      { number: 60, title: 'Less Talk More Rokk', artist: 'Freezepop', ano: '2006', versao: 'Guitar Hero II' },
      { number: 61, title: 'Jordan', artist: 'Buckethead', ano: '2006', versao: 'Guitar Hero II' },
      { number: 62, title: 'Mr. Fix-It', artist: 'The Amazing Growns', ano: '2000', versao: 'Guitar Hero II' },
      { number: 63, title: 'The New Black', artist: 'Every Time I Die', ano: '2005', versao: 'Guitar Hero II' },
      { number: 64, title: 'One For The Road', artist: 'The Braking Wheel', ano: '2005', versao: 'Guitar Hero II' },
      { number: 65, title: 'Parasite', artist: 'The Neighborhoods', ano: '2006', versao: 'Guitar Hero II' },
      { number: 66, title: 'Radium Eyes', artist: 'Count Zero', ano: '2005', versao: 'Guitar Hero II' },
      { number: 67, title: 'Red Lottery', artist: 'Megasus', ano: '2006', versao: 'Guitar Hero II' },
      { number: 68, title: 'Six', artist: 'All That Remains', ano: '2006', versao: 'Guitar Hero II' },
      { number: 69, title: 'Soy Bomb', artist: 'Honest Bob And The Factory-To-Dealer Incentives', ano: '2006', versao: 'Guitar Hero II' },
      { number: 70, title: 'The Light That Blinds', artist: 'Shadows Fall', ano: '2004', versao: 'Guitar Hero II' },
      { number: 71, title: 'Thunderhorse', artist: 'Dethklok', ano: '2006', versao: 'Guitar Hero II' },
      { number: 72, title: 'Trogdor', artist: 'Strong Bad', ano: '2006', versao: 'Guitar Hero II' },
      { number: 73, title: 'X-Stream', artist: 'Voivod', ano: '2006', versao: 'Guitar Hero II' },
      { number: 74, title: 'Yes We Can', artist: 'Made In Mexico', ano: '2005', versao: 'Guitar Hero II' },
      { number: 75, title: 'Famous Last Words', artist: 'My Chemical Romance', ano: '2006', versao: 'Guitar Hero II' },
      { number: 76, title: 'Teenagers', artist: 'My Chemical Romance', ano: '2006', versao: 'Guitar Hero II' },
      { number: 77, title: 'This is How I Disappear', artist: 'My Chemical Romance', ano: '2006', versao: 'Guitar Hero II' },
      { number: 78, title: 'Bury The Hatchet', artist: 'Protest The Hero', ano: '2005', versao: 'Guitar Hero II' },
      { number: 79, title: 'Detonation', artist: 'Trivium', ano: '2006', versao: 'Guitar Hero II' },
      { number: 80, title: 'Ex\'s And Oh\'s', artist: 'Atreyu', ano: '2006', versao: 'Guitar Hero II' },
      { number: 81, title: 'Sin Documentos', artist: 'Los Rodriguez', ano: '1993', versao: 'Guitar Hero II' },
      { number: 82, title: 'Sept', artist: 'Pleymo', ano: '2006', versao: 'Guitar Hero II' },
      { number: 83, title: 'Exile', artist: 'Soilwork', ano: '2007', versao: 'Guitar Hero II' },
      { number: 84, title: 'Memories Of The Grove', artist: 'Maylene And The Sons Of Disaster', ano: '2007', versao: 'Guitar Hero II' },
      { number: 85, title: 'State Of MassaChusetts', artist: 'Dropkick Murphys', ano: '2007', versao: 'Guitar Hero II' },
      { number: 86, title: 'You Should Be Ashamed Of Myself', artist: 'The Bled', ano: '2007', versao: 'Guitar Hero II' }
    ]
  },
  {
    id: '3',
    title: 'Guitar Hero III',
    coverImage: "./images/guitarheroiii2.png",
    platform: 'PlayStation 2',
    releaseDate: '2007-10-28',
    description: 'Lendas do Rock.',
    tracks: [
      { number: 1, title: 'Slow Ride', artist: 'Foghat', ano: '1975', versao: 'Guitar Hero III' },
      { number: 2, title: 'Talk Dirty To Me', artist: 'Poison', ano: '1986', versao: 'Guitar Hero III' },
      { number: 3, title: 'Hit Me With Your Best Shot', artist: 'Pat Benatar', ano: '1980', versao: 'Guitar Hero III' },
      { number: 4, title: 'Story Of My Life', artist: 'Social Distortion', ano: '1990', versao: 'Guitar Hero III' },
      { number: 5, title: 'Rock And Roll All Nite', artist: 'Kiss', ano: '1975', versao: 'Guitar Hero III' },
      { number: 6, title: 'Sabotage', artist: 'Beastie Boys', ano: '1994', versao: 'Guitar Hero III' },
      { number: 7, title: 'Mississippi Queen', artist: 'Mountain', ano: '1970', versao: 'Guitar Hero III' },
      { number: 8, title: 'School\'s Out', artist: 'Alice Cooper', ano: '1972', versao: 'Guitar Hero III' },
      { number: 9, title: 'Sunshine Of Your Love', artist: 'Cream', ano: '1968', versao: 'Guitar Hero III' },
      { number: 10, title: 'Barracuda', artist: 'Heart', ano: '1977', versao: 'Guitar Hero III' },
      { number: 11, title: 'Guitar Battle', artist: 'Tom Morello', ano: '2007', versao: 'Guitar Hero III' },
      { number: 12, title: 'Bulls On Parade', artist: 'Rage Against the Machine', ano: '1996', versao: 'Guitar Hero III' },
      { number: 13, title: 'Reptilia', artist: 'The Strokes', ano: '2003', versao: 'Guitar Hero III' },
      { number: 14, title: 'When You Were Young', artist: 'The Killers', ano: '2006', versao: 'Guitar Hero III' },
      { number: 15, title: 'Miss Murder', artist: 'AFI', ano: '2006', versao: 'Guitar Hero III' },
      { number: 16, title: 'The Seeker', artist: 'The Who', ano: '1971', versao: 'Guitar Hero III' },
      { number: 17, title: 'Lay Down', artist: 'Priestess', ano: '2006', versao: 'Guitar Hero III' },
      { number: 18, title: 'Paint It, Black', artist: 'The Rolling Stones', ano: '1966', versao: 'Guitar Hero III' },
      { number: 19, title: 'Suck My Kiss', artist: 'Red Hot Chili Peppers', ano: '1991', versao: 'Guitar Hero III' },
      { number: 20, title: 'Paranoid', artist: 'Black Sabbath', ano: '1970', versao: 'Guitar Hero III' },
      { number: 21, title: 'Anarchy In The U.K.', artist: 'The Sex Pistols', ano: '2007', versao: 'Guitar Hero III' },
      { number: 22, title: 'Kool Thing', artist: 'Sonic Youth', ano: '1990', versao: 'Guitar Hero III' },
      { number: 23, title: 'My Name Is Jonas', artist: 'Weezer', ano: '1994', versao: 'Guitar Hero III' },
      { number: 24, title: 'Even Flow', artist: 'Pearl Jam', ano: '1991', versao: 'Guitar Hero III' },
      { number: 25, title: 'Cities on Flame with Rock and Roll', artist: 'Blue Oyster Cult', ano: '1972', versao: 'Guitar Hero III' },
      { number: 26, title: 'Holiday In Cambodia', artist: 'The Dead Kennedys', ano: '1980', versao: 'Guitar Hero III' },
      { number: 27, title: 'Rock You Like A Hurricane', artist: 'Scorpions', ano: '1984', versao: 'Guitar Hero III' },
      { number: 28, title: 'Same Old Song And Dance', artist: 'Aerosmith', ano: '1974', versao: 'Guitar Hero III' },
      { number: 29, title: 'La Grange', artist: 'ZZ Top', ano: '1973', versao: 'Guitar Hero III' },
      { number: 30, title: 'Guitar Battle', artist: 'Slash', ano: '2007', versao: 'Guitar Hero III' },
      { number: 31, title: 'Welcome To The Jungle', artist: 'Guns N\' Roses', ano: '1987', versao: 'Guitar Hero III' },
      { number: 32, title: 'Helicopter', artist: 'Bloc Party', ano: '2005', versao: 'Guitar Hero III' },
      { number: 33, title: 'Black Magic Woman', artist: 'Santana', ano: '1970', versao: 'Guitar Hero III' },
      { number: 34, title: 'Cherub Rock', artist: 'The Smashing Pumpkins', ano: '1993', versao: 'Guitar Hero III' },
      { number: 35, title: 'Black Sunshine', artist: 'White Zombie', ano: '1992', versao: 'Guitar Hero III' },
      { number: 36, title: 'The Metal', artist: 'Tenacious D', ano: '2006', versao: 'Guitar Hero III' },
      { number: 37, title: 'Pride And Joy', artist: 'Stevie Ray Vaughan', ano: '1983', versao: 'Guitar Hero III' },
      { number: 38, title: 'Monsters', artist: 'Matchbook Romance', ano: '2006', versao: 'Guitar Hero III' },
      { number: 39, title: 'Before I Forget', artist: 'Slipknot', ano: '2004', versao: 'Guitar Hero III' },
      { number: 40, title: 'Stricken', artist: 'Disturbed', ano: '2005', versao: 'Guitar Hero III' },
      { number: 41, title: '3\'s & 7\'s', artist: 'Queens Of The Stone Age', ano: '2007', versao: 'Guitar Hero III' },
      { number: 42, title: 'Knights Of Cydonia', artist: 'Muse', ano: '2006', versao: 'Guitar Hero III' },
      { number: 43, title: 'PlaceHolder - Credits Song', artist: 'Credits', ano: '2007', versao: 'Guitar Hero III' },
      { number: 44, title: 'Raining Blood', artist: 'Slayer', ano: '1986', versao: 'Guitar Hero III' },
      { number: 45, title: 'Cliffs Of Dover', artist: 'Eric Johnson', ano: '1990', versao: 'Guitar Hero III' },
      { number: 46, title: 'The Number Of The Beast', artist: 'Iron Maiden', ano: '1982', versao: 'Guitar Hero III' },
      { number: 47, title: 'One', artist: 'Metallica', ano: '1988', versao: 'Guitar Hero III' },
      { number: 48, title: 'Avalancha', artist: 'Heroes Del Silencio', ano: '1995', versao: 'Guitar Hero III' },
      { number: 49, title: 'In the Belly Of A Shark', artist: 'Gallows', ano: '2006', versao: 'Guitar Hero III' },
      { number: 50, title: 'Can\'t Be Saved', artist: 'Senses Fail', ano: '2006', versao: 'Guitar Hero III' },
      { number: 51, title: 'Closer', artist: 'Lacuna Coil', ano: '2006', versao: 'Guitar Hero III' },
      { number: 52, title: 'Don\'t Hold Back', artist: 'The Sleeping', ano: '2006', versao: 'Guitar Hero III' },
      { number: 53, title: 'Down \'N Dirty', artist: 'LA Slum Lords', ano: '2007', versao: 'Guitar Hero III' },
      { number: 54, title: 'F.C.P.R.E.M.I.X.', artist: 'The Fall Of Troy', ano: '2005', versao: 'Guitar Hero III' },
      { number: 55, title: 'Generation Rock', artist: 'Revolverheld', ano: '2005', versao: 'Guitar Hero III' },
      { number: 56, title: 'Go That Far', artist: 'Bret Michaels Band', ano: '2006', versao: 'Guitar Hero III' },
      { number: 57, title: 'Hier Kommt Alex', artist: 'Die Toten Hosen', ano: '1988', versao: 'Guitar Hero III' },
      { number: 58, title: 'I\'m In The Band', artist: 'Hellacopters', ano: '2005', versao: 'Guitar Hero III' },
      { number: 59, title: 'Impulse', artist: 'And Endless Sporadic', ano: '2007', versao: 'Guitar Hero III' },
      { number: 60, title: 'In Love', artist: 'Scouts Of St. Sebastian', ano: '2007', versao: 'Guitar Hero III' },
      { number: 61, title: 'Mauvais Garçon', artist: 'Naast', ano: '2007', versao: 'Guitar Hero III' },
      { number: 62, title: 'Metal Heavy Lady', artist: 'Lions', ano: '2007', versao: 'Guitar Hero III' },
      { number: 63, title: 'Minus Celsius', artist: 'Backyard Babies', ano: '2003', versao: 'Guitar Hero III' },
      { number: 64, title: 'My Curse', artist: 'Killswitch Engage', ano: '2006', versao: 'Guitar Hero III' },
      { number: 65, title: 'Nothing For Me Here', artist: 'Dope', ano: '2007', versao: 'Guitar Hero III' },
      { number: 66, title: 'Prayer Of The Refugee', artist: 'Rise Against', ano: '2006', versao: 'Guitar Hero III' },
      { number: 67, title: 'Radio Song', artist: 'Superbus', ano: '2004', versao: 'Guitar Hero III' },
      { number: 68, title: 'Ruby', artist: 'Kaiser Chiefs', ano: '2007', versao: 'Guitar Hero III' },
      { number: 69, title: 'She Bangs The Drums', artist: 'The Stone Roses', ano: '1989', versao: 'Guitar Hero III' },
      { number: 70, title: 'Take This Life', artist: 'In Flames', ano: '2006', versao: 'Guitar Hero III' },
      { number: 71, title: 'The Way It Ends', artist: 'Prototype', ano: '2006', versao: 'Guitar Hero III' },
      { number: 72, title: 'Through The Fire And Flames', artist: 'DragonForce', ano: '2006', versao: 'Guitar Hero III' }
    ]
  },
  {
    id: '4',
    title: 'Guitar Hero World Tour',
    coverImage: "./images/guitarheroworldtourii.png",
    platform: 'PlayStation 2',
    releaseDate: '2008-10-26',
    description: '',
    tracks: [
            { number: 1, title: 'Livin\' on a Prayer', artist: 'Bon Jovi', ano: '1986', versao: 'Guitar Hero World Tour' },
      { number: 2, title: 'About a Girl (Unplugged)', artist: 'Nirvana', ano: '1994', versao: 'Guitar Hero World Tour' },
      { number: 3, title: 'Mountain Song', artist: 'Jane\'s Addiction', ano: '1988', versao: 'Guitar Hero World Tour' },
      { number: 4, title: 'Beautiful Disaster', artist: '311', ano: '1997', versao: 'Guitar Hero World Tour' },
      { number: 5, title: 'Obstacle 1', artist: 'Interpol', ano: '2002', versao: 'Guitar Hero World Tour' },
      { number: 6, title: 'The One I Love', artist: 'R.E.M.', ano: '1987', versao: 'Guitar Hero World Tour' },
      { number: 7, title: 'Some Might Say', artist: 'Oasis', ano: '1995', versao: 'Guitar Hero World Tour' },
      { number: 8, title: 'Today', artist: 'The Smashing Pumpkins', ano: '1993', versao: 'Guitar Hero World Tour' },
      { number: 9, title: 'What I\'ve Done', artist: 'Linkin Park', ano: '2007', versao: 'Guitar Hero World Tour' },
      { number: 10, title: 'Band on the Run', artist: 'Wings', ano: '1973', versao: 'Guitar Hero World Tour' },
      { number: 11, title: 'You\'re Gonna Say Yeah!', artist: 'HushPuppies', ano: '2005', versao: 'Guitar Hero World Tour' },
      { number: 12, title: 'Up Around the Bend', artist: 'Creedence Clearwater Revival', ano: '1970', versao: 'Guitar Hero World Tour' },
      { number: 13, title: 'No Sleep Till Brooklyn', artist: 'Beastie Boys', ano: '1986', versao: 'Guitar Hero World Tour' },
      { number: 14, title: 'The Joker', artist: 'Steve Miller Band', ano: '1973', versao: 'Guitar Hero World Tour' },
      { number: 15, title: 'Freak on a Leash', artist: 'Korn', ano: '1998', versao: 'Guitar Hero World Tour' },
      { number: 16, title: 'Misery Business', artist: 'Paramore', ano: '2007', versao: 'Guitar Hero World Tour' },
      { number: 17, title: 'Hotel California', artist: 'The Eagles', ano: '1976', versao: 'Guitar Hero World Tour' },
      { number: 18, title: 'Parabola', artist: 'Tool', ano: '2001', versao: 'Guitar Hero World Tour' },
      { number: 19, title: 'Schism', artist: 'Tool', ano: '2001', versao: 'Guitar Hero World Tour' },
      { number: 20, title: 'Vicarious', artist: 'Tool', ano: '2006', versao: 'Guitar Hero World Tour' },
      { number: 21, title: 'Eye of the Tiger', artist: 'Survivor', ano: '1982', versao: 'Guitar Hero World Tour' },
      { number: 22, title: 'Spiderwebs', artist: 'No Doubt', ano: '1995', versao: 'Guitar Hero World Tour' },
      { number: 23, title: 'One Way or Another', artist: 'Blondie', ano: '1978', versao: 'Guitar Hero World Tour' },
      { number: 24, title: 'Do It Again', artist: 'Steely Dan', ano: '1972', versao: 'Guitar Hero World Tour' },
      { number: 25, title: 'Zakk Wylde Guitar Battle', artist: 'Zakk Wylde', ano: '2008', versao: 'Guitar Hero World Tour' },
      { number: 26, title: 'Stillborn', artist: 'Black Label Society', ano: '2003', versao: 'Guitar Hero World Tour' },
      { number: 27, title: 'The Middle', artist: 'Jimmy Eat World', ano: '2001', versao: 'Guitar Hero World Tour' },
      { number: 28, title: 'Hey Man, Nice Shot', artist: 'Filter', ano: '1995', versao: 'Guitar Hero World Tour' },
      { number: 29, title: 'Feel the Pain', artist: 'Dinosaur Jr.', ano: '1994', versao: 'Guitar Hero World Tour' },
      { number: 30, title: 'Dammit', artist: 'Blink-182', ano: '1997', versao: 'Guitar Hero World Tour' },
      { number: 31, title: 'Everlong', artist: 'Foo Fighters', ano: '1997', versao: 'Guitar Hero World Tour' },
      { number: 32, title: 'Heartbreaker', artist: 'Pat Benatar', ano: '1979', versao: 'Guitar Hero World Tour' },
      { number: 33, title: 'American Woman', artist: 'The Guess Who', ano: '1970', versao: 'Guitar Hero World Tour' },
      { number: 34, title: 'Ramblin\' Man', artist: 'The Allman Brothers Band', ano: '1973', versao: 'Guitar Hero World Tour' },
      { number: 35, title: 'Go Your Own Way', artist: 'Fleetwood Mac', ano: '1977', versao: 'Guitar Hero World Tour' },
      { number: 36, title: 'Ted Nugent Guitar Battle', artist: 'Ted Nugent', ano: '2008', versao: 'Guitar Hero World Tour' },
      { number: 37, title: 'Stranglehold', artist: 'Ted Nugent', ano: '1975', versao: 'Guitar Hero World Tour' },
      { number: 38, title: 'L\'Via L\'Viaquez', artist: 'The Mars Volta', ano: '2005', versao: 'Guitar Hero World Tour' },
      { number: 39, title: 'Kick Out the Jams', artist: 'MC5', ano: '1969', versao: 'Guitar Hero World Tour' },
      { number: 40, title: 'Santeria', artist: 'Sublime', ano: '1996', versao: 'Guitar Hero World Tour' },
      { number: 41, title: 'On the Road Again (Live)', artist: 'Willie Nelson', ano: '1980', versao: 'Guitar Hero World Tour' },
      { number: 42, title: 'Love Me Two Times', artist: 'The Doors', ano: '1967', versao: 'Guitar Hero World Tour' },
      { number: 43, title: 'Monsoon', artist: 'Tokio Hotel', ano: '2007', versao: 'Guitar Hero World Tour' },
      { number: 44, title: 'Aggro', artist: 'The Enemy', ano: '2007', versao: 'Guitar Hero World Tour' },
      { number: 45, title: 'Rooftops (A Liberation Broadcast)', artist: 'Lostprophets', ano: '2006', versao: 'Guitar Hero World Tour' },
      { number: 46, title: 'Good God', artist: 'Anouk', ano: '2007', versao: 'Guitar Hero World Tour' },
      { number: 47, title: 'One Armed Scissor', artist: 'At the Drive-In', ano: '2000', versao: 'Guitar Hero World Tour' },
      { number: 48, title: 'The Kill', artist: 'Thirty Seconds to Mars', ano: '2005', versao: 'Guitar Hero World Tour' },
      { number: 49, title: 'Shiver', artist: 'Coldplay', ano: '2000', versao: 'Guitar Hero World Tour' },
      { number: 50, title: 'Rebel Yell', artist: 'Billy Idol', ano: '1983', versao: 'Guitar Hero World Tour' },
      { number: 51, title: 'Demolition Man (Live)', artist: 'Sting', ano: '1981', versao: 'Guitar Hero World Tour' },
      { number: 52, title: 'Beat It', artist: 'Michael Jackson', ano: '1982', versao: 'Guitar Hero World Tour' },
      { number: 53, title: 'Lazy Eye', artist: 'Silversun Pickups', ano: '2006', versao: 'Guitar Hero World Tour' },
      { number: 54, title: 'Too Much, Too Young, Too Fast', artist: 'Airbourne', ano: '2007', versao: 'Guitar Hero World Tour' },
      { number: 55, title: 'Float On', artist: 'Modest Mouse', ano: '2004', versao: 'Guitar Hero World Tour' },
      { number: 56, title: 'Nuvole e Lenzuola', artist: 'Negramaro', ano: '2005', versao: 'Guitar Hero World Tour' },
      { number: 57, title: 'Pretty Vacant', artist: 'Sex Pistols', ano: '1977', versao: 'Guitar Hero World Tour' },
      { number: 58, title: 'Are You Gonna Go My Way', artist: 'Lenny Kravitz', ano: '1993', versao: 'Guitar Hero World Tour' },
      { number: 59, title: 'Sweet Home Alabama (Live)', artist: 'Lynyrd Skynyrd', ano: '1974', versao: 'Guitar Hero World Tour' },
      { number: 60, title: 'Assassin', artist: 'Muse', ano: '2006', versao: 'Guitar Hero World Tour' },
      { number: 61, title: 'Escuela de Calor', artist: 'Radio Futura', ano: '1984', versao: 'Guitar Hero World Tour' },
      { number: 62, title: 'The Wind Cries Mary', artist: 'Jimi Hendrix', ano: '1967', versao: 'Guitar Hero World Tour' },
      { number: 63, title: 'Purple Haze (Live)', artist: 'Jimi Hendrix', ano: '1967', versao: 'Guitar Hero World Tour' },
      { number: 64, title: 'Toy Boy', artist: 'Stuck in the Sound', ano: '2006', versao: 'Guitar Hero World Tour' },
      { number: 65, title: 'Hail to the Freaks', artist: 'Beatsteaks', ano: '2007', versao: 'Guitar Hero World Tour' },
      { number: 66, title: 'Vinternoll2', artist: 'Kent', ano: '2005', versao: 'Guitar Hero World Tour' },
      { number: 67, title: 'Hollywood Nights', artist: 'Bob Seger & The Silver Bullet Band', ano: '1978', versao: 'Guitar Hero World Tour' },
      { number: 68, title: 'Soul Doubt', artist: 'NOFX', ano: '1992', versao: 'Guitar Hero World Tour' },
      { number: 69, title: 'Love Removal Machine', artist: 'The Cult', ano: '1987', versao: 'Guitar Hero World Tour' },
      { number: 70, title: 'Our Truth', artist: 'Lacuna Coil', ano: '2006', versao: 'Guitar Hero World Tour' },
      { number: 71, title: 'Antisocial', artist: 'Trust', ano: '1980', versao: 'Guitar Hero World Tour' },
      { number: 72, title: 'Prisoner of Society', artist: 'The Living End', ano: '1997', versao: 'Guitar Hero World Tour' },
      { number: 73, title: 'Mr. Crowley', artist: 'Ozzy Osbourne', ano: '1980', versao: 'Guitar Hero World Tour' },
      { number: 74, title: 'Crazy Train', artist: 'Ozzy Osbourne', ano: '1980', versao: 'Guitar Hero World Tour' },
      { number: 75, title: 'Re-Education (Through Labor)', artist: 'Rise Against', ano: '2008', versao: 'Guitar Hero World Tour' },
      { number: 76, title: 'La Bamba', artist: 'Los Lobos', ano: '1987', versao: 'Guitar Hero World Tour' },
      { number: 77, title: 'Scream Aim Fire', artist: 'Bullet for My Valentine', ano: '2008', versao: 'Guitar Hero World Tour' },
      { number: 78, title: 'Overkill', artist: 'Motörhead', ano: '1979', versao: 'Guitar Hero World Tour' },
      { number: 79, title: 'Trapped Under Ice', artist: 'Metallica', ano: '1984', versao: 'Guitar Hero World Tour' },
      { number: 80, title: 'B.Y.O.B', artist: 'System of a Down', ano: '2005', versao: 'Guitar Hero World Tour' },
      { number: 81, title: 'Hot for Teacher', artist: 'Van Halen', ano: '1984', versao: 'Guitar Hero World Tour' },
      { number: 82, title: 'Love Spreads', artist: 'The Stone Roses', ano: '1994', versao: 'Guitar Hero World Tour' },
      { number: 83, title: 'Never Too Late', artist: 'The Answer', ano: '2006', versao: 'Guitar Hero World Tour' },
      { number: 84, title: 'Weapon of Choice', artist: 'Black Rebel Motorcycle Club', ano: '2007', versao: 'Guitar Hero World Tour' },
      { number: 85, title: 'Pull Me Under', artist: 'Dream Theater', ano: '1992', versao: 'Guitar Hero World Tour' },
      { number: 86, title: 'Satch Boogie', artist: 'Joe Satriani', ano: '1987', versao: 'Guitar Hero World Tour' }
    ]
  },
  {
    id: '5',
    title: 'Guitar Hero Warriors of Rock',
    coverImage: "./images/guitarherowarriorsofrock.png",
    platform: 'PlayStation 2',
    releaseDate: '2010-09-24',
    description: '',
    tracks: [
      { number: 1, title: 'What Do I Get', artist: 'Buzzcocks', ano: '1978', versao: 'Guitar Hero Warriors of Rock' },
      { number: 2, title: 'We\'re Not Gonna Take It', artist: 'Twisted Sister', ano: '1984', versao: 'Guitar Hero Warriors of Rock' },
      { number: 3, title: 'Cherry Bomb', artist: 'The Runaways', ano: '1976', versao: 'Guitar Hero Warriors of Rock' },
      { number: 4, title: 'Self Esteem', artist: 'The Offspring', ano: '1994', versao: 'Guitar Hero Warriors of Rock' },
      { number: 5, title: 'Motivation', artist: 'Sum 41', ano: '2001', versao: 'Guitar Hero Warriors of Rock' },
      { number: 6, title: 'Re-Ignition (Live)', artist: 'Bad Brains', ano: '1989', versao: 'Guitar Hero Warriors of Rock' },
      { number: 7, title: 'Black Rain', artist: 'Soundgarden', ano: '2010', versao: 'Guitar Hero Warriors of Rock' },
      { number: 8, title: 'Theme from Spiderman', artist: 'The Ramones', ano: '1995', versao: 'Guitar Hero Warriors of Rock' },
      { number: 9, title: 'Bleed It Out', artist: 'Linkin Park', ano: '2007', versao: 'Guitar Hero Warriors of Rock' },
      { number: 10, title: 'Tick Tick Boom', artist: 'The Hives', ano: '2007', versao: 'Guitar Hero Warriors of Rock' },
      { number: 11, title: 'Get Free', artist: 'The Vines', ano: '2002', versao: 'Guitar Hero Warriors of Rock' },
      { number: 12, title: 'Machinehead', artist: 'Bush', ano: '1996', versao: 'Guitar Hero Warriors of Rock' },
      { number: 13, title: 'I Know What I Am', artist: 'Band Of Skulls', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 14, title: 'Again', artist: 'Flyleaf', ano: '2007', versao: 'Guitar Hero Warriors of Rock' },
      { number: 15, title: 'Lasso', artist: 'Phoenix', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 16, title: 'Slow Hands', artist: 'Interpol', ano: '2004', versao: 'Guitar Hero Warriors of Rock' },
      { number: 17, title: 'Wish', artist: 'Nine Inch Nails', ano: '1992', versao: 'Guitar Hero Warriors of Rock' },
      { number: 18, title: 'Uprising', artist: 'Muse', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 19, title: 'Bohemian Rhapsody', artist: 'Queen', ano: '1975', versao: 'Guitar Hero Warriors of Rock' },
      { number: 20, title: 'Seven Nation Army', artist: 'The White Stripes', ano: '2003', versao: 'Guitar Hero Warriors of Rock' },
      { number: 21, title: 'Fascination Street', artist: 'The Cure', ano: '1989', versao: 'Guitar Hero Warriors of Rock' },
      { number: 22, title: 'Losing My Religion', artist: 'R.E.M.', ano: '1991', versao: 'Guitar Hero Warriors of Rock' },
      { number: 23, title: 'Tones of Home', artist: 'Blind Melon', ano: '1992', versao: 'Guitar Hero Warriors of Rock' },
      { number: 24, title: 'No Way Back', artist: 'Foo Fighters', ano: '2005', versao: 'Guitar Hero Warriors of Rock' },
      { number: 25, title: 'Graduate', artist: 'Third Eye Blind', ano: '1997', versao: 'Guitar Hero Warriors of Rock' },
      { number: 26, title: 'Interstate Love Song', artist: 'Stone Temple Pilots', ano: '1994', versao: 'Guitar Hero Warriors of Rock' },
      { number: 27, title: 'How You Remind Me', artist: 'Nickelback', ano: '2001', versao: 'Guitar Hero Warriors of Rock' },
      { number: 28, title: 'Been Caught Stealing', artist: 'Jane\'s Addiction', ano: '1990', versao: 'Guitar Hero Warriors of Rock' },
      { number: 29, title: 'Fortunate Son', artist: 'Creedence Clearwater Revival', ano: '1969', versao: 'Guitar Hero Warriors of Rock' },
      { number: 30, title: 'Lunatic Fringe', artist: 'Red Rider', ano: '1981', versao: 'Guitar Hero Warriors of Rock' },
      { number: 31, title: 'Listen to Her Heart', artist: 'Tom Petty & The Heartbreakers', ano: '1978', versao: 'Guitar Hero Warriors of Rock' },
      { number: 32, title: 'Stray Cat Blues', artist: 'The Rolling Stones', ano: '1968', versao: 'Guitar Hero Warriors of Rock' },
      { number: 33, title: 'Burnin\' for You', artist: 'Blue Öyster Cult', ano: '1981', versao: 'Guitar Hero Warriors of Rock' },
      { number: 34, title: 'Free Ride', artist: 'Edgar Winter', ano: '1972', versao: 'Guitar Hero Warriors of Rock' },
      { number: 35, title: 'Cryin\'', artist: 'Aerosmith', ano: '1993', versao: 'Guitar Hero Warriors of Rock' },
      { number: 36, title: 'Money for Nothing', artist: 'Dire Straits', ano: '1985', versao: 'Guitar Hero Warriors of Rock' },
      { number: 37, title: 'Rockin\' in the Free World', artist: 'Neil Young', ano: '1989', versao: 'Guitar Hero Warriors of Rock' },
      { number: 38, title: 'Children of the Grave', artist: 'Black Sabbath', ano: '1971', versao: 'Guitar Hero Warriors of Rock' },
      { number: 39, title: '2112 Pt. 1 Overture', artist: 'Rush', ano: '1976', versao: 'Guitar Hero Warriors of Rock' },
      { number: 40, title: '2112 Pt. 2 The Temples of Syrinx', artist: 'Rush', ano: '1976', versao: 'Guitar Hero Warriors of Rock' },
      { number: 41, title: '2112 Pt. 3 Discovery', artist: 'Rush', ano: '1976', versao: 'Guitar Hero Warriors of Rock' },
      { number: 42, title: '2112 Pt. 4 Presentation', artist: 'Rush', ano: '1976', versao: 'Guitar Hero Warriors of Rock' },
      { number: 43, title: '2112 Pt. 5 Oracle - The Dream', artist: 'Rush', ano: '1976', versao: 'Guitar Hero Warriors of Rock' },
      { number: 44, title: '2112 Pt. 6 Soliloquy', artist: 'Rush', ano: '1976', versao: 'Guitar Hero Warriors of Rock' },
      { number: 45, title: '2112 Pt. 7 Grand Finale', artist: 'Rush', ano: '1976', versao: 'Guitar Hero Warriors of Rock' },
      { number: 46, title: 'Suffocated', artist: 'Orianthi', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 47, title: 'I\'m Not Okay (I Promise)', artist: 'My Chemical Romance', ano: '2004', versao: 'Guitar Hero Warriors of Rock' },
      { number: 48, title: 'Dance, Dance', artist: 'Fall Out Boy', ano: '2005', versao: 'Guitar Hero Warriors of Rock' },
      { number: 49, title: 'There\'s No Secrets This Year', artist: 'Silversun Pickups', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 50, title: 'It\'s Only Another Parsec', artist: 'Rx Bandits', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 51, title: 'The Feel Good Drag', artist: 'Anberlin', ano: '2008', versao: 'Guitar Hero Warriors of Rock' },
      { number: 52, title: 'The Outsider', artist: 'A Perfect Circle', ano: '2004', versao: 'Guitar Hero Warriors of Rock' },
      { number: 53, title: 'Savior', artist: 'Rise Against', ano: '2008', versao: 'Guitar Hero Warriors of Rock' },
      { number: 54, title: 'Bodies', artist: 'Drowning Pool', ano: '2001', versao: 'Guitar Hero Warriors of Rock' },
      { number: 55, title: 'Waidmanns Heil', artist: 'Rammstein', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 56, title: 'I\'m Broken', artist: 'Pantera', ano: '1994', versao: 'Guitar Hero Warriors of Rock' },
      { number: 57, title: 'Dancing Through Sunday', artist: 'AFI', ano: '2003', versao: 'Guitar Hero Warriors of Rock' },
      { number: 58, title: 'Hard to See', artist: 'Five Finger Death Punch', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 59, title: 'Bloodlines', artist: 'Dethklok', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 60, title: 'Ravenous', artist: 'Atreyu', ano: '2004', versao: 'Guitar Hero Warriors of Rock' },
      { number: 61, title: 'Psychosocial', artist: 'Slipknot', ano: '2008', versao: 'Guitar Hero Warriors of Rock' },
      { number: 62, title: 'Ties That Bind', artist: 'Alter Bridge', ano: '2010', versao: 'Guitar Hero Warriors of Rock' },
      { number: 63, title: 'Calling', artist: 'Strung Out', ano: '2000', versao: 'Guitar Hero Warriors of Rock' },
      { number: 64, title: 'Paranoid (Live)', artist: 'Metallica & Ozzy Osbourne', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 65, title: 'Love Gun', artist: 'KISS', ano: '1977', versao: 'Guitar Hero Warriors of Rock' },
      { number: 66, title: 'No More Mr. Nice Guy', artist: 'Alice Cooper', ano: '1973', versao: 'Guitar Hero Warriors of Rock' },
      { number: 67, title: 'Sharp Dressed Man (Live)', artist: 'ZZ Top', ano: '1983', versao: 'Guitar Hero Warriors of Rock' },
      { number: 68, title: 'Scumbag Blues', artist: 'Them Crooked Vultures', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 69, title: 'Feels Like the First Time', artist: 'Foreigner', ano: '1977', versao: 'Guitar Hero Warriors of Rock' },
      { number: 70, title: 'Aqualung', artist: 'Jethro Tull', ano: '1971', versao: 'Guitar Hero Warriors of Rock' },
      { number: 71, title: 'Move It On Over (Live)', artist: 'George Thorogood & The Destroyers', ano: '1978', versao: 'Guitar Hero Warriors of Rock' },
      { number: 72, title: 'Call Me the Breeze (Live)', artist: 'Lynyrd Skynyrd', ano: '1974', versao: 'Guitar Hero Warriors of Rock' },
      { number: 73, title: 'Renegade', artist: 'Styx', ano: '1978', versao: 'Guitar Hero Warriors of Rock' },
      { number: 74, title: 'Pour Some Sugar on Me (Live)', artist: 'Def Leppard', ano: '1987', versao: 'Guitar Hero Warriors of Rock' },
      { number: 75, title: 'Jet City Woman', artist: 'Queensrÿche', ano: '1990', versao: 'Guitar Hero Warriors of Rock' },
      { number: 76, title: 'Ghost', artist: 'Slash featuring Ian Astbury', ano: '2010', versao: 'Guitar Hero Warriors of Rock' },
      { number: 77, title: 'Unskinny Bop', artist: 'Poison', ano: '1990', versao: 'Guitar Hero Warriors of Rock' },
      { number: 78, title: 'Modern Day Cowboy', artist: 'Tesla', ano: '1986', versao: 'Guitar Hero Warriors of Rock' },
      { number: 79, title: '(You Can Still) Rock in America', artist: 'Night Ranger', ano: '1983', versao: 'Guitar Hero Warriors of Rock' },
      { number: 80, title: 'Burn', artist: 'Deep Purple', ano: '1974', versao: 'Guitar Hero Warriors of Rock' },
      { number: 81, title: 'Indians', artist: 'Anthrax', ano: '1987', versao: 'Guitar Hero Warriors of Rock' },
      { number: 82, title: 'Bat Country', artist: 'Avenged Sevenfold', ano: '2005', versao: 'Guitar Hero Warriors of Rock' },
      { number: 83, title: 'Holy Wars... The Punishment Due', artist: 'Megadeth', ano: '1990', versao: 'Guitar Hero Warriors of Rock' },
      { number: 84, title: 'This Day We Fight!', artist: 'Megadeth', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 85, title: 'Sudden Death', artist: 'Megadeth', ano: '2010', versao: 'Guitar Hero Warriors of Rock' },
      { number: 86, title: 'Setting Fire to Sleeping Giants', artist: 'The Dillinger Escape Plan', ano: '2004', versao: 'Guitar Hero Warriors of Rock' },
      { number: 87, title: 'Chemical Warfare', artist: 'Slayer', ano: '1984', versao: 'Guitar Hero Warriors of Rock' },
      { number: 88, title: 'Deadfall', artist: 'Snot', ano: '1997', versao: 'Guitar Hero Warriors of Rock' },
      { number: 89, title: 'If You Want Peace... Prepare for War', artist: 'Children Of Bodom', ano: '2005', versao: 'Guitar Hero Warriors of Rock' },
      { number: 90, title: 'Nemesis', artist: 'Arch Enemy', ano: '2005', versao: 'Guitar Hero Warriors of Rock' },
      { number: 91, title: 'Speeding (Vault Version)', artist: 'Steve Vai', ano: '2009', versao: 'Guitar Hero Warriors of Rock' },
      { number: 92, title: 'Fury of the Storm', artist: 'DragonForce', ano: '2004', versao: 'Guitar Hero Warriors of Rock' },
      { number: 93, title: 'Black Widow of La Porte', artist: 'John 5 Featuring Jim Root', ano: '2007', versao: 'Guitar Hero Warriors of Rock' }
    ]
  },
  {
    id: '6',
    title: 'Guitar Hero 5',
    coverImage: "./images/guitarherov.png",
    platform: 'PlayStation 2',
    releaseDate: '2009-09-01',
    description: '',
    tracks: [
            { number: 1, title: 'Song 2', artist: 'Blur', ano: '1997', versao: 'Guitar Hero 5' },
      { number: 2, title: 'They Say', artist: 'Scars on Broadway', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 3, title: 'Gamma Ray', artist: 'Beck', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 4, title: 'In My Place', artist: 'Coldplay', ano: '2002', versao: 'Guitar Hero 5' },
      { number: 5, title: 'Feel Good Inc', artist: 'Gorillaz', ano: '2005', versao: 'Guitar Hero 5' },
      { number: 6, title: 'All Along The Watchtower', artist: 'Bob Dylan', ano: '1967', versao: 'Guitar Hero 5' },
      { number: 7, title: 'Sympathy For The Devil', artist: 'The Rolling Stones', ano: '1968', versao: 'Guitar Hero 5' },
      { number: 8, title: 'Steady, As She Goes', artist: 'The Raconteurs', ano: '2006', versao: 'Guitar Hero 5' },
      { number: 9, title: 'Blue Day', artist: 'Darker My Love', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 10, title: 'Gratitude', artist: 'Beastie Boys', ano: '1992', versao: 'Guitar Hero 5' },
      { number: 11, title: 'Sowing Season (Yeah)', artist: 'Brand New', ano: '2006', versao: 'Guitar Hero 5' },
      { number: 12, title: 'Only Happy When It Rains', artist: 'Garbage', ano: '1995', versao: 'Guitar Hero 5' },
      { number: 13, title: 'Blue Orchid', artist: 'The White Stripes', ano: '2005', versao: 'Guitar Hero 5' },
      { number: 14, title: 'Hurts So Good', artist: 'John Mellencamp', ano: '1982', versao: 'Guitar Hero 5' },
      { number: 15, title: 'Play That Funky Music', artist: 'Wild Cherry', ano: '1976', versao: 'Guitar Hero 5' },
      { number: 16, title: 'Fame', artist: 'David Bowie', ano: '1975', versao: 'Guitar Hero 5' },
      { number: 17, title: 'Ex-Girlfriend', artist: 'No Doubt', ano: '2000', versao: 'Guitar Hero 5' },
      { number: 18, title: 'Cigarettes, Wedding Bands', artist: 'Band of Horses', ano: '2007', versao: 'Guitar Hero 5' },
      { number: 19, title: 'Woman From Tokyo (\'99 Remix)', artist: 'Deep Purple', ano: '1973', versao: 'Guitar Hero 5' },
      { number: 20, title: 'Under Pressure', artist: 'Queen & David Bowie', ano: '1981', versao: 'Guitar Hero 5' },
      { number: 21, title: 'Sex on Fire', artist: 'Kings of Leon', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 22, title: 'Kryptonite', artist: '3 Doors Down', ano: '2000', versao: 'Guitar Hero 5' },
      { number: 23, title: 'Send A Little Love Token', artist: 'The Duke Spirit', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 24, title: 'Mirror People', artist: 'Love and Rockets', ano: '1988', versao: 'Guitar Hero 5' },
      { number: 25, title: 'Comedown', artist: 'Bush', ano: '1995', versao: 'Guitar Hero 5' },
      { number: 26, title: 'Never Miss A Beat', artist: 'Kaiser Chiefs', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 27, title: 'Dancing With Myself', artist: 'Billy Idol', ano: '1981', versao: 'Guitar Hero 5' },
      { number: 28, title: 'Shout It Out Loud', artist: 'KISS', ano: '1976', versao: 'Guitar Hero 5' },
      { number: 29, title: 'You Give Love A Bad Name', artist: 'Bon Jovi', ano: '1986', versao: 'Guitar Hero 5' },
      { number: 30, title: 'In The Meantime', artist: 'Spacehog', ano: '1995', versao: 'Guitar Hero 5' },
      { number: 31, title: 'You And Me', artist: 'Attack! Attack!', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 32, title: 'L.A.', artist: 'Elliott Smith', ano: '2000', versao: 'Guitar Hero 5' },
      { number: 33, title: 'Make It Wit Chu', artist: 'Queens of the Stone Age', ano: '2007', versao: 'Guitar Hero 5' },
      { number: 34, title: 'Plug In Baby', artist: 'Muse', ano: '2001', versao: 'Guitar Hero 5' },
      { number: 35, title: 'Superstition', artist: 'Stevie Wonder', ano: '1972', versao: 'Guitar Hero 5' },
      { number: 36, title: 'Sultans Of Swing', artist: 'Dire Straits', ano: '1978', versao: 'Guitar Hero 5' },
      { number: 37, title: 'Why Bother?', artist: 'Weezer', ano: '1996', versao: 'Guitar Hero 5' },
      { number: 38, title: 'Jailbreak', artist: 'Thin Lizzy', ano: '1976', versao: 'Guitar Hero 5' },
      { number: 39, title: 'The Rock Show', artist: 'Blink-182', ano: '2001', versao: 'Guitar Hero 5' },
      { number: 40, title: 'Bleed American', artist: 'Jimmy Eat World', ano: '2001', versao: 'Guitar Hero 5' },
      { number: 41, title: 'Hungry Like The Wolf', artist: 'Duran Duran', ano: '1982', versao: 'Guitar Hero 5' },
      { number: 42, title: 'Looks That Kill', artist: 'Mötley Crüe', ano: '1983', versao: 'Guitar Hero 5' },
      { number: 43, title: 'Lonely Is The Night', artist: 'Billy Squier', ano: '1981', versao: 'Guitar Hero 5' },
      { number: 44, title: 'Wannabe In L.A.', artist: 'Eagles of Death Metal', ano: '2009', versao: 'Guitar Hero 5' },
      { number: 45, title: 'Nearly Lost You', artist: 'Screaming Trees', ano: '1992', versao: 'Guitar Hero 5' },
      { number: 46, title: 'Smells Like Teen Spirit', artist: 'Nirvana', ano: '1991', versao: 'Guitar Hero 5' },
      { number: 47, title: 'Lithium (Live)', artist: 'Nirvana', ano: '1992', versao: 'Guitar Hero 5' },
      { number: 48, title: 'All The Pretty Faces', artist: 'The Killers', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 49, title: '20th Century Boy', artist: 'T. Rex', ano: '1973', versao: 'Guitar Hero 5' },
      { number: 50, title: 'What I Got', artist: 'Sublime', ano: '1996', versao: 'Guitar Hero 5' },
      { number: 51, title: 'A-Punk', artist: 'Vampire Weekend', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 52, title: 'Seven', artist: 'Sunny Day Real Estate', ano: '1994', versao: 'Guitar Hero 5' },
      { number: 53, title: 'Bring The Noise 20XX', artist: 'Public Enemy Featuring Zakk Wylde', ano: '2007', versao: 'Guitar Hero 5' },
      { number: 54, title: 'Du Hast', artist: 'Rammstein', ano: '1997', versao: 'Guitar Hero 5' },
      { number: 55, title: 'Ring of Fire', artist: 'Johnny Cash', ano: '1963', versao: 'Guitar Hero 5' },
      { number: 56, title: 'Disconnected', artist: 'Face to Face', ano: '1992', versao: 'Guitar Hero 5' },
      { number: 57, title: 'Bullet With Butterfly Wings', artist: 'The Smashing Pumpkins', ano: '1995', versao: 'Guitar Hero 5' },
      { number: 58, title: 'One Big Holiday', artist: 'My Morning Jacket', ano: '2003', versao: 'Guitar Hero 5' },
      { number: 59, title: 'We’re An American Band', artist: 'Grand Funk Railroad', ano: '1973', versao: 'Guitar Hero 5' },
      { number: 60, title: 'Incinerate', artist: 'Sonic Youth', ano: '2006', versao: 'Guitar Hero 5' },
      { number: 61, title: 'Maiden, Mother and Crone', artist: 'The Sword', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 62, title: 'Wolf Like Me', artist: 'TV on the Radio', ano: '2006', versao: 'Guitar Hero 5' },
      { number: 63, title: 'So Lonely', artist: 'The Police', ano: '1978', versao: 'Guitar Hero 5' },
      { number: 64, title: 'No One To Depend On (Live)', artist: 'Santana', ano: '1971', versao: 'Guitar Hero 5' },
      { number: 65, title: 'Runnin\' Down A Dream', artist: 'Tom Petty', ano: '1989', versao: 'Guitar Hero 5' },
      { number: 66, title: 'Saturday Night’s Alright (For Fighting)', artist: 'Elton John', ano: '1973', versao: 'Guitar Hero 5' },
      { number: 67, title: 'Younk Funk', artist: 'The Derek Trucks Band', ano: '2009', versao: 'Guitar Hero 5' },
      { number: 68, title: 'Sneak Out', artist: 'Rose Hill Drive', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 69, title: 'Streamline Woman', artist: 'Gov’t Mule', ano: '2009', versao: 'Guitar Hero 5' },
      { number: 70, title: 'Back Round', artist: 'Wolfmother', ano: '2009', versao: 'Guitar Hero 5' },
      { number: 71, title: 'Medicate', artist: 'AFI', ano: '2009', versao: 'Guitar Hero 5' },
      { number: 72, title: 'Six Days A Week', artist: 'The Bronx', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 73, title: 'American Girl', artist: 'Tom Petty & the Heartbreakers', ano: '1976', versao: 'Guitar Hero 5' },
      { number: 74, title: 'Judith', artist: 'A Perfect Circle', ano: '2000', versao: 'Guitar Hero 5' },
      { number: 75, title: 'Deadbolt', artist: 'Thrice', ano: '2002', versao: 'Guitar Hero 5' },
      { number: 76, title: 'Brianstorm', artist: 'Arctic Monkeys', ano: '2007', versao: 'Guitar Hero 5' },
      { number: 77, title: '2 Minutes To Midnight', artist: 'Iron Maiden', ano: '1984', versao: 'Guitar Hero 5' },
      { number: 78, title: 'Lust For Life (Live)', artist: 'Iggy Pop', ano: '1977', versao: 'Guitar Hero 5' },
      { number: 79, title: 'Sweating Bullets', artist: 'Megadeth', ano: '1992', versao: 'Guitar Hero 5' },
      { number: 80, title: 'Do You Feel Like We Do? (Live)', artist: 'Peter Frampton', ano: '1976', versao: 'Guitar Hero 5' },
      { number: 81, title: 'Demon(s)', artist: 'Darkest Hour', ano: '2007', versao: 'Guitar Hero 5' },
      { number: 82, title: 'Scatterbrain', artist: 'Jeff Beck', ano: '1975', versao: 'Guitar Hero 5' },
      { number: 83, title: 'Done With Everything, Die For Nothing', artist: 'Children Of Bodom', ano: '2008', versao: 'Guitar Hero 5' },
      { number: 84, title: 'The Spirit Of Radio (Live)', artist: 'Rush', ano: '1980', versao: 'Guitar Hero 5' },
      { number: 85, title: '21st Century Schizoid Man', artist: 'King Crimson', ano: '1969', versao: 'Guitar Hero 5' }
    ]
  },
    {
    id: '7',
    title: 'Guitar Hero Aerosmith',
    coverImage: "./images/guitarheroaerosmith.png",
    platform: 'PlayStation 2',
    releaseDate: '2008-06-28',
    description: '',
    tracks: [
      { number: 1, title: 'Dream Police', artist: 'Cheap Trick', ano: '1979', versao: 'Guitar Hero: Aerosmith' },
      { number: 2, title: 'All the Young Dudes', artist: 'Mott the Hoople', ano: '1972', versao: 'Guitar Hero: Aerosmith' },
      { number: 3, title: 'Make It', artist: 'Aerosmith', ano: '1973', versao: 'Guitar Hero: Aerosmith' },
      { number: 4, title: 'Uncle Salty', artist: 'Aerosmith', ano: '1975', versao: 'Guitar Hero: Aerosmith' },
      { number: 5, title: 'Draw The Line', artist: 'Aerosmith', ano: '1977', versao: 'Guitar Hero: Aerosmith' },
      { number: 6, title: 'I Hate Myself for Loving You', artist: 'Joan Jett and the Blackhearts', ano: '1988', versao: 'Guitar Hero: Aerosmith' },
      { number: 7, title: 'All Day and All of the Night', artist: 'The Kinks', ano: '1964', versao: 'Guitar Hero: Aerosmith' },
      { number: 8, title: 'Movin\' Out', artist: 'Aerosmith', ano: '1973', versao: 'Guitar Hero: Aerosmith' },
      { number: 9, title: 'No Surprize', artist: 'Aerosmith', ano: '1979', versao: 'Guitar Hero: Aerosmith' },
      { number: 10, title: 'Sweet Emotion', artist: 'Aerosmith', ano: '1975', versao: 'Guitar Hero: Aerosmith' },
      { number: 11, title: 'Complete Control', artist: 'The Clash', ano: '1977', versao: 'Guitar Hero: Aerosmith' },
      { number: 12, title: 'Personality Crisis', artist: 'New York Dolls', ano: '1973', versao: 'Guitar Hero: Aerosmith' },
      { number: 13, title: 'Livin\' on the Edge', artist: 'Aerosmith', ano: '1993', versao: 'Guitar Hero: Aerosmith' },
      { number: 14, title: 'Ragdoll', artist: 'Aerosmith', ano: '1987', versao: 'Guitar Hero: Aerosmith' },
      { number: 15, title: 'Love in an Elevator', artist: 'Aerosmith', ano: '1989', versao: 'Guitar Hero: Aerosmith' },
      { number: 16, title: 'Always on the Run', artist: 'Lenny Kravitz', ano: '1991', versao: 'Guitar Hero: Aerosmith' },
      { number: 17, title: 'Hard to Handle', artist: 'The Black Crowes', ano: '1990', versao: 'Guitar Hero: Aerosmith' },
      { number: 18, title: 'Back in the Saddle', artist: 'Aerosmith', ano: '1976', versao: 'Guitar Hero: Aerosmith' },
      { number: 19, title: 'Beyond Beautiful', artist: 'Aerosmith', ano: '2001', versao: 'Guitar Hero: Aerosmith' },
      { number: 20, title: 'Dream On', artist: 'Aerosmith', ano: '1973', versao: 'Guitar Hero: Aerosmith' },
      { number: 21, title: 'She Sells Sanctuary', artist: 'The Cult', ano: '1985', versao: 'Guitar Hero: Aerosmith' },
      { number: 22, title: 'King of Rock', artist: 'Run-D.M.C.', ano: '1985', versao: 'Guitar Hero: Aerosmith' },
      { number: 23, title: 'Bright Light Fright', artist: 'Aerosmith', ano: '1977', versao: 'Guitar Hero: Aerosmith' },
      { number: 24, title: 'Nobody\'s Fault', artist: 'Aerosmith', ano: '1976', versao: 'Guitar Hero: Aerosmith' },
      { number: 25, title: 'Walk This Way', artist: 'Run-D.M.C. Featuring Aerosmith', ano: '1986', versao: 'Guitar Hero: Aerosmith' },
      { number: 26, title: 'Cat Scratch Fever', artist: 'Ted Nugent', ano: '1977', versao: 'Guitar Hero: Aerosmith' },
      { number: 27, title: 'Sex Type Thing', artist: 'Stone Temple Pilots', ano: '1992', versao: 'Guitar Hero: Aerosmith' },
      { number: 28, title: 'Mama Kin', artist: 'Aerosmith', ano: '1973', versao: 'Guitar Hero: Aerosmith' },
      { number: 29, title: 'Toys in the Attic', artist: 'Aerosmith', ano: '1975', versao: 'Guitar Hero: Aerosmith' },
      { number: 30, title: 'Train Kept A-Rollin\'', artist: 'Aerosmith', ano: '1974', versao: 'Guitar Hero: Aerosmith' },
      { number: 31, title: 'Mercy', artist: 'Joe Perry', ano: '2005', versao: 'Guitar Hero: Aerosmith' },
      { number: 32, title: 'Shakin\' My Cage', artist: 'Joe Perry', ano: '2005', versao: 'Guitar Hero: Aerosmith' },
      { number: 33, title: 'Talk Talkin\'', artist: 'Joe Perry', ano: '2005', versao: 'Guitar Hero: Aerosmith' },
      { number: 34, title: 'Combination', artist: 'Aerosmith', ano: '1976', versao: 'Guitar Hero: Aerosmith' },
      { number: 35, title: 'Kings and Queens', artist: 'Aerosmith', ano: '1977', versao: 'Guitar Hero: Aerosmith' },
      { number: 36, title: 'Rats in the Cellar', artist: 'Aerosmith', ano: '1976', versao: 'Guitar Hero: Aerosmith' },
      { number: 37, title: 'Let the Music Do the Talking', artist: 'Aerosmith', ano: '1985', versao: 'Guitar Hero: Aerosmith' },
      { number: 38, title: 'Pandora\'s Box', artist: 'Aerosmith', ano: '1975', versao: 'Guitar Hero: Aerosmith' },
      { number: 39, title: 'Pink', artist: 'Aerosmith', ano: '1997', versao: 'Guitar Hero: Aerosmith' },
      { number: 40, title: 'Walk This Way', artist: 'Aerosmith', ano: '1975', versao: 'Guitar Hero: Aerosmith' }
    ]
  },
   {
    id: '8',
    title: 'Guitar Hero Metalica',
    coverImage: "./images/guitarherometalica.png",
    platform: 'PlayStation 2',
    releaseDate: '2009-03-29',
    description: '',
    tracks: [
      { number: 1, title: 'For Whom the Bell Tolls', artist: 'Metallica', ano: '1984', versao: 'Guitar Hero: Metallica' },
      { number: 2, title: 'The Unforgiven', artist: 'Metallica', ano: '1991', versao: 'Guitar Hero: Metallica' },
      { number: 3, title: 'Mother of Mercy', artist: 'Samhain', ano: '1986', versao: 'Guitar Hero: Metallica' },
      { number: 4, title: 'Turn the Page (Live)', artist: 'Bob Seger & The Silver Bullet Band', ano: '1976', versao: 'Guitar Hero: Metallica' },
      { number: 5, title: 'No Excuses', artist: 'Alice in Chains', ano: '1994', versao: 'Guitar Hero: Metallica' },
      { number: 6, title: 'Tuesday’s Gone', artist: 'Lynyrd Skynyrd', ano: '1973', versao: 'Guitar Hero: Metallica' },
      { number: 7, title: 'Albatross', artist: 'Corrosion of Conformity', ano: '2005', versao: 'Guitar Hero: Metallica' },
      { number: 8, title: 'Nothing Else Matters', artist: 'Metallica', ano: '1991', versao: 'Guitar Hero: Metallica' },
      { number: 9, title: 'Enter Sandman', artist: 'Metallica', ano: '1991', versao: 'Guitar Hero: Metallica' },
      { number: 10, title: 'Orion', artist: 'Metallica', ano: '1986', versao: 'Guitar Hero: Metallica' },
      { number: 11, title: 'No Leaf Clover', artist: 'Metallica', ano: '1999', versao: 'Guitar Hero: Metallica' },
      { number: 12, title: 'The Boys Are Back in Town', artist: 'Thin Lizzy', ano: '1976', versao: 'Guitar Hero: Metallica' },
      { number: 13, title: 'Stacked Actors', artist: 'Foo Fighters', ano: '1999', versao: 'Guitar Hero: Metallica' },
      { number: 14, title: 'The Black River', artist: 'The Sword', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 15, title: 'War Inside My Head', artist: 'Suicidal Tendencies', ano: '1987', versao: 'Guitar Hero: Metallica' },
      { number: 16, title: 'Toxicity', artist: 'System of a Down', ano: '2001', versao: 'Guitar Hero: Metallica' },
      { number: 17, title: 'Sad But True', artist: 'Metallica', ano: '1991', versao: 'Guitar Hero: Metallica' },
      { number: 18, title: 'The Memory Remains', artist: 'Metallica', ano: '1997', versao: 'Guitar Hero: Metallica' },
      { number: 19, title: 'Fuel', artist: 'Metallica', ano: '1997', versao: 'Guitar Hero: Metallica' },
      { number: 20, title: 'Wherever I May Roam', artist: 'Metallica', ano: '1991', versao: 'Guitar Hero: Metallica' },
      { number: 21, title: 'Welcome Home (Sanitarium)', artist: 'Metallica', ano: '1986', versao: 'Guitar Hero: Metallica' },
      { number: 22, title: 'Demon Cleaner', artist: 'Kyuss', ano: '1994', versao: 'Guitar Hero: Metallica' },
      { number: 23, title: 'Stone Cold Crazy', artist: 'Queen', ano: '1974', versao: 'Guitar Hero: Metallica' },
      { number: 24, title: 'Mommy’s Little Monster (Live)', artist: 'Social Distortion', ano: '1983', versao: 'Guitar Hero: Metallica' },
      { number: 25, title: 'Armed and Ready', artist: 'Michael Schenker Group', ano: '1980', versao: 'Guitar Hero: Metallica' },
      { number: 26, title: 'Hell Bent for Leather', artist: 'Judas Priest', ano: '1978', versao: 'Guitar Hero: Metallica' },
      { number: 27, title: 'Frantic', artist: 'Metallica', ano: '2003', versao: 'Guitar Hero: Metallica' },
      { number: 28, title: 'Fade to Black', artist: 'Metallica', ano: '1984', versao: 'Guitar Hero: Metallica' },
      { number: 29, title: 'All Nightmare Long', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 30, title: 'Mercyful Fate', artist: 'Mercyful Fate', ano: '1982', versao: 'Guitar Hero: Metallica' },
      { number: 31, title: 'Whiplash', artist: 'Metallica', ano: '1983', versao: 'Guitar Hero: Metallica' },
      { number: 32, title: 'Blood and Thunder', artist: 'Mastodon', ano: '2004', versao: 'Guitar Hero: Metallica' },
      { number: 33, title: 'Beautiful Mourning', artist: 'Machine Head', ano: '2003', versao: 'Guitar Hero: Metallica' },
      { number: 34, title: 'Ace of Spades', artist: 'Motörhead', ano: '1980', versao: 'Guitar Hero: Metallica' },
      { number: 35, title: 'Hit the Lights', artist: 'Metallica', ano: '1983', versao: 'Guitar Hero: Metallica' },
      { number: 36, title: 'Seek and Destroy', artist: 'Metallica', ano: '1983', versao: 'Guitar Hero: Metallica' },
      { number: 37, title: 'Creeping Death', artist: 'Metallica', ano: '1984', versao: 'Guitar Hero: Metallica' },
      { number: 38, title: 'Master of Puppets', artist: 'Metallica', ano: '1986', versao: 'Guitar Hero: Metallica' },
      { number: 39, title: 'Battery', artist: 'Metallica', ano: '1986', versao: 'Guitar Hero: Metallica' },
      { number: 40, title: 'Am I Evil?', artist: 'Diamond Head', ano: '1980', versao: 'Guitar Hero: Metallica' },
      { number: 41, title: 'Evil', artist: 'Mercyful Fate', ano: '1983', versao: 'Guitar Hero: Metallica' },
      { number: 42, title: 'War Ensemble', artist: 'Slayer', ano: '1990', versao: 'Guitar Hero: Metallica' },
      { number: 43, title: 'One', artist: 'Metallica', ano: '1988', versao: 'Guitar Hero: Metallica' },
      { number: 44, title: 'The Shortest Straw', artist: 'Metallica', ano: '1988', versao: 'Guitar Hero: Metallica' },
      { number: 45, title: 'Dyer’s Eve', artist: 'Metallica', ano: '1988', versao: 'Guitar Hero: Metallica' },
      { number: 46, title: 'Disposable Heroes', artist: 'Metallica', ano: '1986', versao: 'Guitar Hero: Metallica' },
      { number: 47, title: 'Fight Fire with Fire', artist: 'Metallica', ano: '1984', versao: 'Guitar Hero: Metallica' },
      { number: 48, title: 'The Thing That Should Not Be', artist: 'Metallica', ano: '1986', versao: 'Guitar Hero: Metallica' },
      { number: 49, title: 'That Was Just Your Life', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 50, title: 'The End of the Line', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 51, title: 'Broken, Beat & Scarred', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 52, title: 'The Day That Never Comes', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 53, title: 'All Nightmare Long', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 54, title: 'Cyanide', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 55, title: 'The Unforgiven III', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 56, title: 'The Judas Kiss', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 57, title: 'Suicide & Redemption J.H.', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 58, title: 'Suicide & Redemption K.H.', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' },
      { number: 59, title: 'My Apocalypse', artist: 'Metallica', ano: '2008', versao: 'Guitar Hero: Metallica' }
    ]
  },
  {
    id: '9',
    title: 'Rock Band I',
    coverImage: "./images/rockbandi1.png",
    platform: 'PlayStation 2',
    releaseDate: '2007-10-20',
    description: '',
    tracks: [
      { number: 1, title: 'Should I Stay or Should I Go', artist: 'The Clash', ano: '1982', versao: 'Rock Band I' },
      { number: 2, title: 'In Bloom', artist: 'Nirvana', ano: '1991', versao: 'Rock Band I' },
      { number: 3, title: 'Maps', artist: 'Yeah Yeah Yeahs', ano: '2003', versao: 'Rock Band I' },
      { number: 4, title: 'Mississippi Queen', artist: 'Mountain', ano: '1970', versao: 'Rock Band I' },
      { number: 5, title: 'Here It Goes Again', artist: 'OK Go', ano: '2005', versao: 'Rock Band I' },
      { number: 6, title: 'Blitzkrieg Bop', artist: 'Ramones', ano: '1976', versao: 'Rock Band I' },
      { number: 7, title: 'Wave of Mutilation', artist: 'Pixies', ano: '1989', versao: 'Rock Band I' },
      { number: 8, title: 'I Think I\'m Paranoid', artist: 'Garbage', ano: '1998', versao: 'Rock Band I' },
      { number: 9, title: 'Orange Crush', artist: 'R.E.M.', ano: '1988', versao: 'Rock Band I' },
      { number: 10, title: 'The Hand That Feeds', artist: 'Nine Inch Nails', ano: '2005', versao: 'Rock Band I' },
      { number: 11, title: 'Sabotage', artist: 'Beastie Boys', ano: '1994', versao: 'Rock Band I' },
      { number: 12, title: 'Say It Ain’t So', artist: 'Weezer', ano: '1994', versao: 'Rock Band I' },
      { number: 13, title: 'Learn to Fly', artist: 'Foo Fighters', ano: '1999', versao: 'Rock Band I' },
      { number: 14, title: 'Go With the Flow', artist: 'Queens of the Stone Age', ano: '2002', versao: 'Rock Band I' },
      { number: 15, title: 'Detroit Rock City', artist: 'Kiss', ano: '1976', versao: 'Rock Band I' },
      { number: 16, title: 'Creep', artist: 'Radiohead', ano: '1993', versao: 'Rock Band I' },
      { number: 17, title: 'When You Were Young', artist: 'The Killers', ano: '2006', versao: 'Rock Band I' },
      { number: 18, title: 'Celebrity Skin', artist: 'Hole', ano: '1998', versao: 'Rock Band I' },
      { number: 19, title: 'Electric Version', artist: 'The New Pornographers', ano: '2003', versao: 'Rock Band I' },
      { number: 20, title: 'Gimme Shelter', artist: 'The Rolling Stones', ano: '1969', versao: 'Rock Band I' },
      { number: 21, title: 'Suffragette City', artist: 'David Bowie', ano: '1972', versao: 'Rock Band I' },
      { number: 22, title: 'Black Hole Sun', artist: 'Soundgarden', ano: '1994', versao: 'Rock Band I' },
      { number: 23, title: 'Main Offender', artist: 'The Hives', ano: '2000', versao: 'Rock Band I' },
      { number: 24, title: 'Reptilia', artist: 'The Strokes', ano: '2003', versao: 'Rock Band I' },
      { number: 25, title: 'Epic', artist: 'Faith No More', ano: '1989', versao: 'Rock Band I' },
      { number: 26, title: 'Are You Gonna Be My Girl', artist: 'Jet', ano: '2003', versao: 'Rock Band I' },
      { number: 27, title: 'Dani California', artist: 'Red Hot Chili Peppers', ano: '2006', versao: 'Rock Band I' },
      { number: 28, title: '(Don\'t Fear) The Reaper', artist: 'Blue Oyster Cult', ano: '1976', versao: 'Rock Band I' },
      { number: 29, title: 'Paranoid', artist: 'Black Sabbath', ano: '1970', versao: 'Rock Band I' },
      { number: 30, title: 'Wanted Dead Or Alive', artist: 'Bon Jovi', ano: '1986', versao: 'Rock Band I' },
      { number: 31, title: 'Ballroom Blitz', artist: 'Sweet', ano: '1974', versao: 'Rock Band I' },
      { number: 32, title: 'Dead On Arrival', artist: 'Fall Out Boy', ano: '2003', versao: 'Rock Band I' },
      { number: 33, title: 'Vasoline', artist: 'Stone Temple Pilots', ano: '1994', versao: 'Rock Band I' },
      { number: 34, title: 'Next To You', artist: 'The Police', ano: '1978', versao: 'Rock Band I' },
      { number: 35, title: 'Won\'t Get Fooled Again', artist: 'The Who', ano: '1971', versao: 'Rock Band I' },
      { number: 36, title: 'Tom Sawyer', artist: 'Rush', ano: '1981', versao: 'Rock Band I' },
      { number: 37, title: 'Foreplay/Long Time', artist: 'Boston', ano: '1976', versao: 'Rock Band I' },
      { number: 38, title: 'Cherub Rock', artist: 'Smashing Pumpkins', ano: '1993', versao: 'Rock Band I' },
      { number: 39, title: 'Enter Sandman', artist: 'Metallica', ano: '1991', versao: 'Rock Band I' },
      { number: 40, title: 'Welcome Home', artist: 'Coheed & Cambria', ano: '2005', versao: 'Rock Band I' },
      { number: 41, title: 'Highway Star', artist: 'Deep Purple', ano: '1972', versao: 'Rock Band I' },
      { number: 42, title: 'Flirtin\' With Disaster', artist: 'Molly Hatchet', ano: '1979', versao: 'Rock Band I' },
      { number: 43, title: 'Train Kept A Rollin\'', artist: 'Aerosmith', ano: '1974', versao: 'Rock Band I' },
      { number: 44, title: 'Run To The Hills', artist: 'Iron Maiden', ano: '1982', versao: 'Rock Band I' },
      { number: 45, title: 'Green Grass & High Tides', artist: 'The Outlaws', ano: '1975', versao: 'Rock Band I' },
      { number: 46, title: 'Time We Had', artist: 'The Mother Hips', ano: '2007', versao: 'Rock Band I' },
      { number: 47, title: 'Day Late, Dollar Short', artist: 'The Acro-Brats', ano: '2006', versao: 'Rock Band I' },
      { number: 48, title: 'Seven', artist: 'Vagiant', ano: '2007', versao: 'Rock Band I' },
      { number: 49, title: '29 Fingers', artist: 'The Konks', ano: '2005', versao: 'Rock Band I' },
      { number: 50, title: 'I\'m So Sick', artist: 'Flyleaf', ano: '2005', versao: 'Rock Band I' },
      { number: 51, title: 'Blood Doll', artist: 'Anarchy Club', ano: '2007', versao: 'Rock Band I' },
      { number: 52, title: 'Nightmare', artist: 'Crooked X', ano: '2007', versao: 'Rock Band I' },
      { number: 53, title: 'I Get By', artist: 'Honest Bob & The Factory-to-dealer Incentives', ano: '2004', versao: 'Rock Band I' },
      { number: 54, title: 'Outside', artist: 'Tribe', ano: '1990', versao: 'Rock Band I' },
      { number: 55, title: 'Brainpower', artist: 'Freezepop', ano: '2007', versao: 'Rock Band I' },
      { number: 56, title: 'Can\'t Let Go', artist: 'Death Of The Cool', ano: '2007', versao: 'Rock Band I' },
      { number: 57, title: 'Timmy & The Lords Of The Underworld', artist: 'Timmy & The Lords Of The Underworld', ano: '2000', versao: 'Rock Band I' },
      { number: 58, title: 'Pleasure (Pleasure)', artist: 'Bang Camaro', ano: '2007', versao: 'Rock Band I' },
      { number: 59, title: 'Roxanne', artist: 'The Police', ano: '1978', versao: 'Rock Band I' },
      { number: 60, title: 'Dirty Little Secrets', artist: 'The All-American Rejects', ano: '2005', versao: 'Rock Band I' },
      { number: 61, title: 'Rockaway Beach', artist: 'Ramones', ano: '1977', versao: 'Rock Band I' },
      { number: 62, title: 'Roam', artist: 'The B-52s', ano: '1989', versao: 'Rock Band I' },
      { number: 63, title: 'Don\'t Look Back In Anger', artist: 'Oasis', ano: '1995', versao: 'Rock Band I' },
      { number: 64, title: 'Beetlebum', artist: 'Blur', ano: '1997', versao: 'Rock Band I' },
      { number: 65, title: 'Monsoon', artist: 'Tokio Hotel', ano: '2007', versao: 'Rock Band I' },
      { number: 66, title: 'Countdown To Insanity', artist: 'H-Blockx', ano: '2007', versao: 'Rock Band I' },
      { number: 67, title: 'Manu Chao', artist: 'Les Wampas', ano: '2003', versao: 'Rock Band I' },
      { number: 68, title: 'Perfekte Welle', artist: 'Juli', ano: '2004', versao: 'Rock Band I' },
      { number: 69, title: 'New Wave', artist: 'Pleymo', ano: '2002', versao: 'Rock Band I' },
      { number: 70, title: 'Rock \'N\' Roll Star', artist: 'Oasis', ano: '1994', versao: 'Rock Band I' },
      { number: 71, title: 'Hysteria', artist: 'Muse', ano: '2003', versao: 'Rock Band I' },
      { number: 72, title: 'Hier Kommt Alex', artist: 'Die Toten Hosen', ano: '1988', versao: 'Rock Band I' }
    ]
  },
    {
    id: '10',
    title: 'Rock Band II',
    coverImage: "./images/rockbandii2.png",
    platform: 'PlayStation 2',
    releaseDate: '2008-09-14',
    description: '',
    tracks: [
      { number: 1, title: 'Eye Of The Tiger', artist: 'Survivor', ano: '1982', versao: 'Rock Band II' },
      { number: 2, title: 'Float On', artist: 'Modest Mouse', ano: '2004', versao: 'Rock Band II' },
      { number: 3, title: 'Today', artist: 'Smashing Pumpkins', ano: '1993', versao: 'Rock Band II' },
      { number: 4, title: 'Hungry Like A Wolf', artist: 'Duran Duran', ano: '1982', versao: 'Rock Band II' },
      { number: 5, title: 'Cool For Cats', artist: 'Squeeze', ano: '1979', versao: 'Rock Band II' },
      { number: 6, title: 'Pretend We\'Re Dead', artist: 'L7', ano: '1992', versao: 'Rock Band II' },
      { number: 7, title: 'My Own Worst Enemy', artist: 'Lit', ano: '1999', versao: 'Rock Band II' },
      { number: 8, title: 'One Step Closer', artist: 'Linkin Park', ano: '2000', versao: 'Rock Band II' },
      { number: 9, title: 'We Got The Beat', artist: 'The Go-Go\'S', ano: '1981', versao: 'Rock Band II' },
      { number: 10, title: 'That\'S What You Get', artist: 'Paramore', ano: '2007', versao: 'Rock Band II' },
      { number: 11, title: 'Rebel Girl', artist: 'Bikini Kill', ano: '1993', versao: 'Rock Band II' },
      { number: 12, title: 'So What\'Cha Want', artist: 'Beastie Boys', ano: '1992', versao: 'Rock Band II' },
      { number: 13, title: 'Drain You', artist: 'Nirvana', ano: '1991', versao: 'Rock Band II' },
      { number: 14, title: 'New Kid In School', artist: 'The Donnas', ano: '2007', versao: 'Rock Band II' },
      { number: 15, title: 'Hello There', artist: 'Cheap Trick', ano: '1977', versao: 'Rock Band II' },
      { number: 16, title: 'Lump', artist: 'Presidents Of The United States Of America', ano: '1995', versao: 'Rock Band II' },
      { number: 17, title: 'American Woman', artist: 'The Guess Who', ano: '1970', versao: 'Rock Band II' },
      { number: 18, title: 'I Was Wrong', artist: 'Social Distortion', ano: '1996', versao: 'Rock Band II' },
      { number: 19, title: 'Nine In The Afternoon', artist: 'Panic! At The Disco', ano: '2008', versao: 'Rock Band II' },
      { number: 20, title: 'Mountain Song', artist: 'Jane\'S Addiction', ano: '1988', versao: 'Rock Band II' },
      { number: 21, title: 'Man In The Box', artist: 'Alice In Chains', ano: '1991', versao: 'Rock Band II' },
      { number: 22, title: 'Our Truth', artist: 'Lacuna Coil', ano: '2006', versao: 'Rock Band II' },
      { number: 23, title: 'White Wedding (Part 1)', artist: 'Billy Idol', ano: '1982', versao: 'Rock Band II' },
      { number: 24, title: 'E-Pro', artist: 'Beck', ano: '2005', versao: 'Rock Band II' },
      { number: 25, title: 'Psycho Killer', artist: 'Talking Heads', ano: '1977', versao: 'Rock Band II' },
      { number: 26, title: 'Spirit In The Sky', artist: 'Norman Greenbaum', ano: '1969', versao: 'Rock Band II' },
      { number: 27, title: 'Kids In America', artist: 'The Muffs', ano: '1995', versao: 'Rock Band II' },
      { number: 28, title: 'Feel The Pain', artist: 'Dinosaur Jr.', ano: '1994', versao: 'Rock Band II' },
      { number: 29, title: 'Give It Away', artist: 'Red Hot Chili Peppers', ano: '1991', versao: 'Rock Band II' },
      { number: 30, title: 'Conventional Lover', artist: 'Speck', ano: '2007', versao: 'Rock Band II' },
      { number: 31, title: 'A Jagged Gorgeous Winter', artist: 'The Main Drag', ano: '2008', versao: 'Rock Band II' },
      { number: 32, title: 'Bad Reputation', artist: 'Joan Jett', ano: '1980', versao: 'Rock Band II' },
      { number: 33, title: 'Pump It Up', artist: 'Elvis Costello', ano: '1978', versao: 'Rock Band II' },
      { number: 34, title: 'You Outta Know', artist: 'Alanis Morissette', ano: '1995', versao: 'Rock Band II' },
      { number: 35, title: 'Go Your Own Way', artist: 'Fleetwood Mac', ano: '1977', versao: 'Rock Band II' },
      { number: 36, title: 'Welcome To The Neighborhood', artist: 'The Libyans', ano: '2008', versao: 'Rock Band II' },
      { number: 37, title: 'Pda', artist: 'Interpol', ano: '2002', versao: 'Rock Band II' },
      { number: 38, title: 'Shooting Star', artist: 'Bad Company', ano: '1975', versao: 'Rock Band II' },
      { number: 39, title: 'Livin\' On A Prayer', artist: 'Bon Jovi', ano: '1986', versao: 'Rock Band II' },
      { number: 40, title: 'De-Luxe', artist: 'Lush', ano: '1990', versao: 'Rock Band II' },
      { number: 41, title: 'Girls Not Grey', artist: 'Afi', ano: '2003', versao: 'Rock Band II' },
      { number: 42, title: 'One Way Or Another', artist: 'Blondie', ano: '1978', versao: 'Rock Band II' },
      { number: 43, title: 'Tangled Up In Blue', artist: 'Bob Dylan', ano: '1975', versao: 'Rock Band II' },
      { number: 44, title: 'Alex Chilton', artist: 'The Replacements', ano: '1987', versao: 'Rock Band II' },
      { number: 45, title: 'Alive', artist: 'Pearl Jam', ano: '1991', versao: 'Rock Band II' },
      { number: 46, title: 'The Middle', artist: 'Jimmy Eat World', ano: '2001', versao: 'Rock Band II' },
      { number: 47, title: 'Aqualung', artist: 'Jethro Tull', ano: '1971', versao: 'Rock Band II' },
      { number: 48, title: 'Supreme Girl', artist: 'The Sterns', ano: '2006', versao: 'Rock Band II' },
      { number: 49, title: 'Down With The Sickness', artist: 'Disturbed', ano: '2000', versao: 'Rock Band II' },
      { number: 50, title: 'Give It All', artist: 'Rise Against', ano: '2004', versao: 'Rock Band II' },
      { number: 51, title: 'Where\'D You Go', artist: 'The Mighty Mighty Bosstones', ano: '1991', versao: 'Rock Band II' },
      { number: 52, title: 'Come Out And Play (Keep \'Em Separated)', artist: 'The Offspring', ano: '1994', versao: 'Rock Band II' },
      { number: 53, title: 'Everlong', artist: 'Foo Fighters', ano: '1997', versao: 'Rock Band II' },
      { number: 54, title: 'Pinball Wizard', artist: 'The Who', ano: '1969', versao: 'Rock Band II' },
      { number: 55, title: 'Rob The Prez-O-Dent', artist: 'That Handsome Devil', ano: '2008', versao: 'Rock Band II' },
      { number: 56, title: 'Testify', artist: 'Rage Against The Machine', ano: '1999', versao: 'Rock Band II' },
      { number: 57, title: 'Uncontrollable Urge', artist: 'Devo', ano: '1978', versao: 'Rock Band II' },
      { number: 58, title: 'Any Way You Want It', artist: 'Journey', ano: '1980', versao: 'Rock Band II' },
      { number: 59, title: 'Round And Round', artist: 'Ratt', ano: '1984', versao: 'Rock Band II' },
      { number: 60, title: 'Night Lies', artist: 'Bang Camaro', ano: '2008', versao: 'Rock Band II' },
      { number: 61, title: 'Let There Be Rock', artist: 'Ac/Dc', ano: '1977', versao: 'Rock Band II' },
      { number: 62, title: 'Alabama Getaway', artist: 'Grateful Dead', ano: '1980', versao: 'Rock Band II' },
      { number: 63, title: 'Lazy Eye', artist: 'Silversun Pickups', ano: '2006', versao: 'Rock Band II' },
      { number: 64, title: 'Teen Age Riot', artist: 'Sonic Youth', ano: '1988', versao: 'Rock Band II' },
      { number: 65, title: 'The Trees (Vault Edition)', artist: 'Rush', ano: '1978', versao: 'Rock Band II' },
      { number: 66, title: 'Carry On Wayward Son', artist: 'Kansas', ano: '1976', versao: 'Rock Band II' },
      { number: 67, title: 'Rock\'N Me', artist: 'Steve Miller Band', ano: '1976', versao: 'Rock Band II' },
      { number: 68, title: 'Ace Of Spades \'08', artist: 'Motorhead', ano: '2008', versao: 'Rock Band II' },
      { number: 69, title: 'Spoonman', artist: 'Soundgarden', ano: '1994', versao: 'Rock Band II' },
      { number: 70, title: 'Almost Easy', artist: 'Avenged Sevenfold', ano: '2007', versao: 'Rock Band II' },
      { number: 71, title: 'Chop Suey', artist: 'System Of A Down', ano: '2001', versao: 'Rock Band II' },
      { number: 72, title: 'Shackler\'S Revenge', artist: 'Guns N\' Roses', ano: '2008', versao: 'Rock Band II' },
      { number: 73, title: 'Master Exploder', artist: 'Tenacious D', ano: '2006', versao: 'Rock Band II' },
      { number: 74, title: 'Ramblin\' Man', artist: 'The Allman Brothers Band', ano: '1973', versao: 'Rock Band II' },
      { number: 75, title: 'Shoulder To The Plow', artist: 'Breaking Wheel', ano: '2008', versao: 'Rock Band II' },
      { number: 76, title: 'Get Clean', artist: 'Anarchy Club', ano: '2009', versao: 'Rock Band II' },
      { number: 77, title: 'Colony Of Birchmen', artist: 'Mastodon', ano: '2006', versao: 'Rock Band II' },
      { number: 78, title: 'Peace Sells', artist: 'Megadeth', ano: '1986', versao: 'Rock Band II' },
      { number: 79, title: 'Souls Of Black', artist: 'Testament', ano: '1990', versao: 'Rock Band II' },
      { number: 80, title: 'Bodhisattva', artist: 'Steely Dan', ano: '1973', versao: 'Rock Band II' },
      { number: 81, title: 'Battery', artist: 'Metallica', ano: '1986', versao: 'Rock Band II' },
      { number: 82, title: 'Panic Attack', artist: 'Dream Theater', ano: '2005', versao: 'Rock Band II' },
      { number: 83, title: 'Visions', artist: 'Abnormality', ano: '2007', versao: 'Rock Band II' },
      { number: 84, title: 'Painkiller', artist: 'Judas Priest', ano: '1990', versao: 'Rock Band II' }
    ]
  }
];