import { Album } from '../types/Album';

export const fetchAlbums = async (): Promise<Album[]> => [
  {
    id: '1',
    title: 'Guitar Hero I',
    coverImage: "./images/guitarheroi.png",
    platform: 'PlayStation 2',
    releaseDate: '08/11/2005',
    description: 'O primeiro Guitar Hero.',
    tracks: [
      { number: 1, title: 'I Love Rock And Roll', artist: 'Joan Jett', ano: '1982', versao: 'Guitar Hero I' },
      { number: 2, title: 'I Wanna Be Sedated', artist: 'The Ramones', ano: '1978', versao: 'Guitar Hero I' },
      { number: 3, title: 'Thunderkiss 65', artist: 'White Zombie', ano: '1978', versao: 'Guitar Hero I' },
      { number: 4, title: 'Smoke On The Water', artist: 'Deep Purple', ano: '1973', versao: 'Guitar Hero I' },
      { number: 5, title: 'Infected', artist: 'Bad Religion', ano: '1994', versao: 'Guitar Hero I' },
      { number: 6, title: 'Iron Man', artist: 'Black Sabbath', ano: '1970', versao: 'Guitar Hero I' },
      { number: 7, title: 'More Than A Feeling', artist: 'Boston', ano: '1976', versao: 'Guitar Hero I' },
      { number: 8, title: 'You Got Another Thing Comin', artist: 'Judas Priest', ano: '1992', versao: 'Guitar Hero I' },
      { number: 9, title: 'Take Me Out', artist: 'Franz Ferdnand', ano: '2004', versao: 'Guitar Hero I' },
      { number: 10, title: 'Sharp Dressed Man', artist: 'ZZ Top', ano: '1993', versao: 'Guitar Hero I' },
      { number: 11, title: 'Killer Queen', artist: 'Queen', ano: '1974', versao: 'Guitar Hero I' },
      { number: 12, title: 'Hey You', artist: 'The Exies', ano: '2004', versao: 'Guitar Hero I' },
      { number: 13, title: 'Stellar', artist: 'Incubus', ano: '1991', versao: 'Guitar Hero I' },
      { number: 14, title: 'Heart Full of Black', artist: 'Burning Brides', ano: '2004', versao: 'Guitar Hero I' },
      { number: 15, title: 'Symphony Of Destruction', artist: 'Megadeth', ano: '1992', versao: 'Guitar Hero I' },
      { number: 16, title: 'Zigg Stardut', artist: 'David Bowie', ano: '1972', versao: 'Guitar Hero I' },
      { number: 17, title: 'Fat Lip', artist: 'Sum 41', ano: '2001', versao: 'Guitar Hero I' },
      { number: 18, title: 'Cochise', artist: 'Audioslave', ano: '2002', versao: 'Guitar Hero I' },
      { number: 19, title: 'Take It Off', artist: 'The Donnas', ano: '2002', versao: 'Guitar Hero I' },
      { number: 20, title: 'Unsung', artist: 'Helmet', ano: '1992', versao: 'Guitar Hero I' },
      { number: 21, title: 'Spanish Castle Magic', artist: 'Jimi Hendrix', ano: '1967', versao: 'Guitar Hero I' },
      { number: 22, title: 'Higher Ground', artist: 'Red Hot Chili Peppers', ano: '1989', versao: 'Guitar Hero I' },
      { number: 23, title: 'No One Knows', artist: 'Queens Of The Stone Age', ano: '2002', versao: 'Guitar Hero I' },
      { number: 24, title: 'Ace Of Spades', artist: 'Motorhead', ano: '1980', versao: 'Guitar Hero I' },
      { number: 25, title: 'Crossroads', artist: 'Cream', ano: '1968', versao: 'Guitar Hero I' },
      { number: 26, title: 'Godzila', artist: 'Blue Oyster Cult', ano: '1977', versao: 'Guitar Hero I' },
      { number: 27, title: 'Texas Flood', artist: 'Stevie Ray Vaugun', ano: '1983', versao: 'Guitar Hero I' },
      { number: 28, title: 'Frankenstein', artist: 'Edgar Winter Group', ano: '1972', versao: 'Guitar Hero I' },
      { number: 29, title: 'Cowboys From Hell', artist: 'Pantera', ano: '1990', versao: 'Guitar Hero I' },
      { number: 30, title: 'Bark At The Moon', artist: 'Ozzy Osbourne', ano: '1983', versao: 'Guitar Hero I' },
      { number: 31, title: 'Fire It Up', artist: 'Black Label Society', ano: '2005', versao: 'Guitar Hero I' },
      { number: 32, title: 'Cheat On The Church', artist: 'Graveyard BBQ', ano: '2005', versao: 'Guitar Hero I' },
      { number: 33, title: 'Caveman Re Joice', artist: 'The Bags', ano: '2005', versao: 'Guitar Hero I' },
      { number: 34, title: 'Eureka! I Found Love', artist: 'The Upper Crust', ano: '2001', versao: 'Guitar Hero I' },
      { number: 35, title: 'All of This', artist: 'Shaimus', ano: '2005', versao: 'Guitar Hero I' },
      { number: 36, title: 'Behind The Mask', artist: 'Anarchy Club', ano: '2005', versao: 'Guitar Hero I' },
      { number: 37, title: 'The Break Wheel', artist: 'Artillery', ano: '2005', versao: 'Guitar Hero I' },
      { number: 38, title: 'Call Out', artist: 'The Agro-Breats', ano: '2005', versao: 'Guitar Hero I' },
      { number: 39, title: 'Decontrol', artist: 'Drist', ano: '2005', versao: 'Guitar Hero I' },
      { number: 40, title: 'Even Rats', artist: 'The Slip', ano: '2006', versao: 'Guitar Hero I' },
      { number: 41, title: 'Farewell Myth', artist: 'Made In Mexico', ano: '2005', versao: 'Guitar Hero I' },
      { number: 42, title: 'Fly On The Wall', artist: 'Din', ano: '2005', versao: 'Guitar Hero I' },
      { number: 43, title: 'Get Ready 2 Rock', artist: 'Freezepop', ano: '2000', versao: 'Guitar Hero I' },
      { number: 44, title: 'Theme From Guitar Hero', artist: 'Monkey Steal The Peach', ano: '2005', versao: 'Guitar Hero I' },
      { number: 45, title: 'Hey', artist: 'Honest Bob And The Factory To Dealer Incentives', ano: '2004', versao: 'Guitar Hero I' },
      { number: 46, title: 'Sail Your Ship By', artist: 'Countzero', ano: '2005', versao: 'Guitar Hero I' },
      { number: 47, title: 'The Story Of My Love', artist: 'The Model Sons', ano: '2005', versao: 'Guitar Hero I' },
      { number: 48, title: 'Trippolette', artist: 'Andrew Buch', ano: '2005', versao: 'Guitar Hero I' },
      { number: 49, title: 'Graveyard Shift', artist: 'Windtunnel Syndrome', ano: '2005', versao: 'Guitar Hero I' }
    ]
  },
  {
    id: '2',
    title: 'Guitar Hero II',
    coverImage: "./images/guitarheroii.png",
    platform: 'PlayStation 2',
    releaseDate: '07/11/2006',
    description: 'O segundo Guitar Hero.',
    tracks: [
      { number: 1, title: 'Surrender', artist: 'Cheap Trick', ano: '1978', versao: 'Guitar Hero II' },
      { number: 2, title: 'Possum Kingdom', artist: 'Toadies', ano: '1994', versao: 'Guitar Hero II' },
      { number: 3, title: 'Heart-Shaped Box', artist: 'Nirvana', ano: '1993', versao: 'Guitar Hero II' },
      { number: 4, title: 'Salvation', artist: 'Rancid', ano: '1995', versao: 'Guitar Hero II' },
      { number: 5, title: 'Strutter', artist: 'Kiss', ano: '1974', versao: 'Guitar Hero II' },
      { number: 6, title: 'Shout At The Devil', artist: 'Motley Crue', ano: '1983', versao: 'Guitar Hero II' },
      { number: 7, title: 'Mother', artist: 'Danzig', ano: '1988', versao: 'Guitar Hero II' },
      { number: 8, title: 'Life Wasted', artist: 'Pearl Jam', ano: '2006', versao: 'Guitar Hero II' },
      { number: 9, title: 'Cherry Die', artist: 'Warrant', ano: '1990', versao: 'Guitar Hero II' },
      { number: 10, title: 'Woman', artist: 'Wolfmother', ano: '2006', versao: 'Guitar Hero II' },
      { number: 11, title: 'You Really Got Me', artist: 'Van Halen', ano: '1978', versao: 'Guitar Hero II' },
      { number: 12, title: 'Tonight I\'m Gonna Rock You Tonight', artist: 'Spinal Tap', ano: '1984', versao: 'Guitar Hero II' },
      { number: 13, title: 'Carry On Wayward Son', artist: 'Kansas', ano: '1976', versao: 'Guitar Hero II' },
      { number: 14, title: 'Search And Destroy', artist: 'Iggy Pop And The Stooges', ano: '1973', versao: 'Guitar Hero II' },
      { number: 15, title: 'Message In A Bottle', artist: 'The Police', ano: '1979', versao: 'Guitar Hero II' },
      { number: 16, title: 'Billion Dollar Babies', artist: 'Alice Cooper', ano: '1973', versao: 'Guitar Hero II' },
      { number: 17, title: 'Them Bones', artist: 'Alice In Chains', ano: '1992', versao: 'Guitar Hero II' },
      { number: 18, title: 'War Pigs', artist: 'Black Sabbath', ano: '1970', versao: 'Guitar Hero II' },
      { number: 19, title: 'Monkey Wrench', artist: 'Foo Fighters', ano: '1997', versao: 'Guitar Hero II' },
      { number: 20, title: 'Hush', artist: 'Deep Purple', ano: '1967', versao: 'Guitar Hero II' },
      { number: 21, title: 'Girlfriend', artist: 'Matthew Sweet', ano: '1990', versao: 'Guitar Hero II' },
      { number: 22, title: 'Who Was In My Room Last NightP', artist: 'Butthole Surfers', ano: '1993', versao: 'Guitar Hero II' },
      { number: 23, title: 'Can\'t You Hear Me Knocking', artist: 'The Rolling Stones', ano: '1971', versao: 'Guitar Hero II' },
      { number: 24, title: 'Sweet Child O\' Mine', artist: 'Guns N\' Roses', ano: '1988', versao: 'Guitar Hero II' },
      { number: 25, title: 'Rock And Roll, Hoochie Koo', artist: 'Johnny Winter', ano: '1970', versao: 'Guitar Hero II' },
      { number: 26, title: 'Tattooed Love Boys', artist: 'The Pretenders', ano: '1980', versao: 'Guitar Hero II' },
      { number: 27, title: 'John The Fisherman', artist: 'Primus', ano: '1990', versao: 'Guitar Hero II' },
      { number: 28, title: 'Jessica', artist: 'The Allman Brothers Band', ano: '1973', versao: 'Guitar Hero II' },
      { number: 29, title: 'Bad Reputation', artist: 'Thin Lizzy', ano: '1977', versao: 'Guitar Hero II' },
      { number: 30, title: 'Last Child', artist: 'Aerosmith', ano: '1976', versao: 'Guitar Hero II' },
      { number: 31, title: 'Crazy On You', artist: 'Heart', ano: '1976', versao: 'Guitar Hero II' },
      { number: 32, title: 'Trippin\' On A Hole In a Paper Heart', artist: 'Stone Temple Pilots', ano: '1996', versao: 'Guitar Hero II' },
      { number: 33, title: 'Dead!', artist: 'My Chemical Romance', ano: '2006', versao: 'Guitar Hero II' },
      { number: 34, title: 'Killing In The Name', artist: 'Reage Against The Machine', ano: '1993', versao: 'Guitar Hero II' },
      { number: 35, title: 'Freya', artist: 'The Sword', ano: '2006', versao: 'Guitar Hero II' },
      { number: 36, title: 'Stop!', artist: 'Jane\'s Addiction', ano: '1990', versao: 'Guitar Hero II' },
      { number: 37, title: 'Madhouse', artist: 'Anthrax', ano: '1985', versao: 'Guitar Hero II' },
      { number: 38, title: 'The Trooper', artist: 'Iron Maiden', ano: '1983', versao: 'Guitar Hero II' },
      { number: 39, title: 'Rock This Town', artist: 'Stray Cats', ano: '1982', versao: 'Guitar Hero II' },
      { number: 40, title: 'Laid To Rest', artist: 'Lamb Of God', ano: '2004', versao: 'Guitar Hero II' },
      { number: 41, title: 'Psychobilly Freakout', artist: 'The Reverend Horton Heat', ano: '1990', versao: 'Guitar Hero II' },
      { number: 42, title: 'YYZ', artist: 'Rush', ano: '1981', versao: 'Guitar Hero II' },
      { number: 43, title: 'Beast And The Harlot', artist: 'Avanged Sevenfold', ano: '2006', versao: 'Guitar Hero II' },
      { number: 44, title: 'Carry Me Home', artist: 'The Living End', ano: '2000', versao: 'Guitar Hero II' },
      { number: 45, title: 'Institutionalized', artist: 'Suicidal Tendencies', ano: '1983', versao: 'Guitar Hero II' },
      { number: 46, title: 'Misirlou', artist: 'Dick Dale', ano: '1962', versao: 'Guitar Hero II' },
      { number: 47, title: 'Hangar 18', artist: 'Megadeth', ano: '1990', versao: 'Guitar Hero II' },
      { number: 48, title: 'Free Bird', artist: 'Lynyrd Skynyrd', ano: '1973', versao: 'Guitar Hero II' },
      { number: 49, title: 'Raw Dog', artist: 'The Last Vegas', ano: '2006', versao: 'Guitar Hero II' },
      { number: 50, title: 'Arterial Black', artist: 'Drist', ano: '2006', versao: 'Guitar Hero II' },
      { number: 51, title: 'Collide', artist: 'Anarchy Club', ano: '2006', versao: 'Guitar Hero II' },
      { number: 52, title: 'Drink Up', artist: 'Ounce Of Self', ano: '2006', versao: 'Guitar Hero II' },
      { number: 53, title: 'Elephant Bones', artist: 'That HandSome Devil', ano: '2005', versao: 'Guitar Hero II' },
      { number: 54, title: 'Fall Of Pangea', artist: 'Valiente Thorr', ano: '2006', versao: 'Guitar Hero II' },
      { number: 55, title: 'FTK', artist: 'Vagiant', ano: '2006', versao: 'Guitar Hero II' },
      { number: 56, title: 'Gemini', artist: 'Brian Kahanek', ano: '2004', versao: 'Guitar Hero II' },
      { number: 57, title: 'Kicked To The Curb', artist: 'Noble Rot', ano: '2006', versao: 'Guitar Hero II' },
      { number: 58, title: 'Push Push (Lady Lightning)', artist: 'Bang Camaro', ano: '2007', versao: 'Guitar Hero II' },
      { number: 59, title: 'Laughtrack', artist: 'The Agro-Brats', ano: '2005', versao: 'Guitar Hero II' },
      { number: 60, title: 'Less Talk More Rokk', artist: 'Freezepop', ano: '2006', versao: 'Guitar Hero II' },
      { number: 61, title: 'Jordan', artist: 'Buckethead', ano: '2006', versao: 'Guitar Hero II' },
      { number: 62, title: 'Mr. Fix-It', artist: 'The Amazing Growns', ano: '2000', versao: 'Guitar Hero II' },
      { number: 63, title: 'The New Black', artist: 'Every Time I Die', ano: '2005', versao: 'Guitar Hero II' },
      { number: 64, title: 'One For The Road', artist: 'The Braking Wheel', ano: '2005', versao: 'Guitar Hero II' },
      { number: 65, title: 'Parasite', artist: 'The Neighborhoods', ano: '2006', versao: 'Guitar Hero II' },
      { number: 66, title: 'Radium Eyes', artist: 'Count Zero', ano: '2005', versao: 'Guitar Hero II' },
      { number: 67, title: 'Red Lottery', artist: 'Megasus', ano: '2006', versao: 'Guitar Hero II' },
      { number: 68, title: 'Six', artist: 'All That Remains', ano: '2006', versao: 'Guitar Hero II' },
      { number: 69, title: 'Soy Bomb', artist: 'Honest Bob And The Factory-To-Dealer Incentives', ano: '2006', versao: 'Guitar Hero II' },
      { number: 70, title: 'The Light That Blinds', artist: 'Shadows Fall', ano: '2004', versao: 'Guitar Hero II' },
      { number: 71, title: 'Thunderhorse', artist: 'Dethklok', ano: '2006', versao: 'Guitar Hero II' },
      { number: 72, title: 'Trogdor', artist: 'Strong Bad', ano: '2006', versao: 'Guitar Hero II' },
      { number: 73, title: 'X-Stream', artist: 'Voivod', ano: '2006', versao: 'Guitar Hero II' },
      { number: 74, title: 'Yes We Can', artist: 'Made In Mexico', ano: '2005', versao: 'Guitar Hero II' },
      { number: 75, title: 'Famous Last Words', artist: 'My Chemical Romance', ano: '2006', versao: 'Guitar Hero II' },
      { number: 76, title: 'Teenagers', artist: 'My Chemical Romance', ano: '2006', versao: 'Guitar Hero II' },
      { number: 77, title: 'This is How I Disappear', artist: 'My Chemical Romance', ano: '2006', versao: 'Guitar Hero II' },
      { number: 78, title: 'Bury The Hatchet', artist: 'Protest The Hero', ano: '2005', versao: 'Guitar Hero II' },
      { number: 79, title: 'Detonation', artist: 'Trivium', ano: '2006', versao: 'Guitar Hero II' },
      { number: 80, title: 'Ex\'s And Oh\'s', artist: 'Atreyu', ano: '2006', versao: 'Guitar Hero II' },
      { number: 81, title: 'Sin Documentos', artist: 'Los Rodriguez', ano: '1993', versao: 'Guitar Hero II' },
      { number: 82, title: 'Sept', artist: 'Pleymo', ano: '2006', versao: 'Guitar Hero II' },
      { number: 83, title: 'Exile', artist: 'Soilwork', ano: '2007', versao: 'Guitar Hero II' },
      { number: 84, title: 'Memories Of The Grove', artist: 'Maylene And The Sons Of Disaster', ano: '2007', versao: 'Guitar Hero II' },
      { number: 85, title: 'State Of MassaChusetts', artist: 'Dropkick Murphys', ano: '2007', versao: 'Guitar Hero II' },
      { number: 86, title: 'You Should Be Ashamed Of Myself', artist: 'The Bled', ano: '2007', versao: 'Guitar Hero II' }
    ]
  },
  {
    id: '3',
    title: 'Guitar Hero III',
    coverImage: "./images/guitarheroiii.png",
    platform: 'PlayStation 2',
    releaseDate: '2007-10-28',
    description: 'Lendas do Rock.',
    tracks: [
      { number: 1, title: 'Slow Ride', artist: 'Foghat', ano: '1975', versao: 'Guitar Hero III' },
      { number: 2, title: 'Talk Dirty To Me', artist: 'Poison', ano: '1986', versao: 'Guitar Hero III' },
      { number: 3, title: 'Hit Me With Your Best Shot', artist: 'Pat Benatar', ano: '1980', versao: 'Guitar Hero III' },
      { number: 4, title: 'Story Of My Life', artist: 'Social Distortion', ano: '1990', versao: 'Guitar Hero III' },
      { number: 5, title: 'Rock And Roll All Nite', artist: 'Kiss', ano: '1975', versao: 'Guitar Hero III' },
      { number: 6, title: 'Sabotage', artist: 'Beastie Boys', ano: '1994', versao: 'Guitar Hero III' },
      { number: 7, title: 'Mississippi Queen', artist: 'Mountain', ano: '1970', versao: 'Guitar Hero III' },
      { number: 8, title: 'School\'s Out', artist: 'Alice Cooper', ano: '1972', versao: 'Guitar Hero III' },
      { number: 9, title: 'Sunshine Of Your Love', artist: 'Cream', ano: '1968', versao: 'Guitar Hero III' },
      { number: 10, title: 'Barracuda', artist: 'Heart', ano: '1977', versao: 'Guitar Hero III' },
      { number: 11, title: 'Guitar Battle', artist: 'Tom Morello', ano: '2007', versao: 'Guitar Hero III' },
      { number: 12, title: 'Bulls On Parade', artist: 'Rage Against the Machine', ano: '1996', versao: 'Guitar Hero III' },
      { number: 13, title: 'Reptilia', artist: 'The Strokes', ano: '2003', versao: 'Guitar Hero III' },
      { number: 14, title: 'When You Were Young', artist: 'The Killers', ano: '2006', versao: 'Guitar Hero III' },
      { number: 15, title: 'Miss Murder', artist: 'AFI', ano: '2006', versao: 'Guitar Hero III' },
      { number: 16, title: 'The Seeker', artist: 'The Who', ano: '1971', versao: 'Guitar Hero III' },
      { number: 17, title: 'Lay Down', artist: 'Priestess', ano: '2006', versao: 'Guitar Hero III' },
      { number: 18, title: 'Paint It, Black', artist: 'The Rolling Stones', ano: '1966', versao: 'Guitar Hero III' },
      { number: 19, title: 'Suck My Kiss', artist: 'Red Hot Chili Peppers', ano: '1991', versao: 'Guitar Hero III' },
      { number: 20, title: 'Paranoid', artist: 'Black Sabbath', ano: '1970', versao: 'Guitar Hero III' },
      { number: 21, title: 'Anarchy In The U.K.', artist: 'The Sex Pistols', ano: '2007', versao: 'Guitar Hero III' },
      { number: 22, title: 'Kool Thing', artist: 'Sonic Youth', ano: '1990', versao: 'Guitar Hero III' },
      { number: 23, title: 'My Name Is Jonas', artist: 'Weezer', ano: '1994', versao: 'Guitar Hero III' },
      { number: 24, title: 'Even Flow', artist: 'Pearl Jam', ano: '1991', versao: 'Guitar Hero III' },
      { number: 25, title: 'Cities on Flame with Rock and Roll', artist: 'Blue Oyster Cult', ano: '1972', versao: 'Guitar Hero III' },
      { number: 26, title: 'Holiday In Cambodia', artist: 'The Dead Kennedys', ano: '1980', versao: 'Guitar Hero III' },
      { number: 27, title: 'Rock You Like A Hurricane', artist: 'Scorpions', ano: '1984', versao: 'Guitar Hero III' },
      { number: 28, title: 'Same Old Song And Dance', artist: 'Aerosmith', ano: '1974', versao: 'Guitar Hero III' },
      { number: 29, title: 'La Grange', artist: 'ZZ Top', ano: '1973', versao: 'Guitar Hero III' },
      { number: 30, title: 'Guitar Battle', artist: 'Slash', ano: '2007', versao: 'Guitar Hero III' },
      { number: 31, title: 'Welcome To The Jungle', artist: 'Guns N\' Roses', ano: '1987', versao: 'Guitar Hero III' },
      { number: 32, title: 'Helicopter', artist: 'Bloc Party', ano: '2005', versao: 'Guitar Hero III' },
      { number: 33, title: 'Black Magic Woman', artist: 'Santana', ano: '1970', versao: 'Guitar Hero III' },
      { number: 34, title: 'Cherub Rock', artist: 'The Smashing Pumpkins', ano: '1993', versao: 'Guitar Hero III' },
      { number: 35, title: 'Black Sunshine', artist: 'White Zombie', ano: '1992', versao: 'Guitar Hero III' },
      { number: 36, title: 'The Metal', artist: 'Tenacious D', ano: '2006', versao: 'Guitar Hero III' },
      { number: 37, title: 'Pride And Joy', artist: 'Stevie Ray Vaughan', ano: '1983', versao: 'Guitar Hero III' },
      { number: 38, title: 'Monsters', artist: 'Matchbook Romance', ano: '2006', versao: 'Guitar Hero III' },
      { number: 39, title: 'Before I Forget', artist: 'Slipknot', ano: '2004', versao: 'Guitar Hero III' },
      { number: 40, title: 'Stricken', artist: 'Disturbed', ano: '2005', versao: 'Guitar Hero III' },
      { number: 41, title: '3\'s & 7\'s', artist: 'Queens Of The Stone Age', ano: '2007', versao: 'Guitar Hero III' },
      { number: 42, title: 'Knights Of Cydonia', artist: 'Muse', ano: '2006', versao: 'Guitar Hero III' },
      { number: 43, title: 'PlaceHolder - Credits Song', artist: 'Credits', ano: '2007', versao: 'Guitar Hero III' },
      { number: 44, title: 'Raining Blood', artist: 'Slayer', ano: '1986', versao: 'Guitar Hero III' },
      { number: 45, title: 'Cliffs Of Dover', artist: 'Eric Johnson', ano: '1990', versao: 'Guitar Hero III' },
      { number: 46, title: 'The Number Of The Beast', artist: 'Iron Maiden', ano: '1982', versao: 'Guitar Hero III' },
      { number: 47, title: 'One', artist: 'Metallica', ano: '1988', versao: 'Guitar Hero III' },
      { number: 48, title: 'Avalancha', artist: 'Heroes Del Silencio', ano: '1995', versao: 'Guitar Hero III' },
      { number: 49, title: 'In the Belly Of A Shark', artist: 'Gallows', ano: '2006', versao: 'Guitar Hero III' },
      { number: 50, title: 'Can\'t Be Saved', artist: 'Senses Fail', ano: '2006', versao: 'Guitar Hero III' },
      { number: 51, title: 'Closer', artist: 'Lacuna Coil', ano: '2006', versao: 'Guitar Hero III' },
      { number: 52, title: 'Don\'t Hold Back', artist: 'The Sleeping', ano: '2006', versao: 'Guitar Hero III' },
      { number: 53, title: 'Down \'N Dirty', artist: 'LA Slum Lords', ano: '2007', versao: 'Guitar Hero III' },
      { number: 54, title: 'F.C.P.R.E.M.I.X.', artist: 'The Fall Of Troy', ano: '2005', versao: 'Guitar Hero III' },
      { number: 55, title: 'Generation Rock', artist: 'Revolverheld', ano: '2005', versao: 'Guitar Hero III' },
      { number: 56, title: 'Go That Far', artist: 'Bret Michaels Band', ano: '2006', versao: 'Guitar Hero III' },
      { number: 57, title: 'Hier Kommt Alex', artist: 'Die Toten Hosen', ano: '1988', versao: 'Guitar Hero III' },
      { number: 58, title: 'I\'m In The Band', artist: 'Hellacopters', ano: '2005', versao: 'Guitar Hero III' },
      { number: 59, title: 'Impulse', artist: 'And Endless Sporadic', ano: '2007', versao: 'Guitar Hero III' },
      { number: 60, title: 'In Love', artist: 'Scouts Of St. Sebastian', ano: '2007', versao: 'Guitar Hero III' },
      { number: 61, title: 'Mauvais Garçon', artist: 'Naast', ano: '2007', versao: 'Guitar Hero III' },
      { number: 62, title: 'Metal Heavy Lady', artist: 'Lions', ano: '2007', versao: 'Guitar Hero III' },
      { number: 63, title: 'Minus Celsius', artist: 'Backyard Babies', ano: '2003', versao: 'Guitar Hero III' },
      { number: 64, title: 'My Curse', artist: 'Killswitch Engage', ano: '2006', versao: 'Guitar Hero III' },
      { number: 65, title: 'Nothing For Me Here', artist: 'Dope', ano: '2007', versao: 'Guitar Hero III' },
      { number: 66, title: 'Prayer Of The Refugee', artist: 'Rise Against', ano: '2006', versao: 'Guitar Hero III' },
      { number: 67, title: 'Radio Song', artist: 'Superbus', ano: '2004', versao: 'Guitar Hero III' },
      { number: 68, title: 'Ruby', artist: 'Kaiser Chiefs', ano: '2007', versao: 'Guitar Hero III' },
      { number: 69, title: 'She Bangs The Drums', artist: 'The Stone Roses', ano: '1989', versao: 'Guitar Hero III' },
      { number: 70, title: 'Take This Life', artist: 'In Flames', ano: '2006', versao: 'Guitar Hero III' },
      { number: 71, title: 'The Way It Ends', artist: 'Prototype', ano: '2006', versao: 'Guitar Hero III' },
      { number: 72, title: 'Through The Fire And Flames', artist: 'DragonForce', ano: '2006', versao: 'Guitar Hero III' }
    ]
  },
  {
    id: '4',
    title: 'Rock Band I',
    coverImage: "./images/rockbandi.png",
    platform: 'PlayStation 2',
    releaseDate: '2007-10-20',
    description: '',
    tracks: [
      { number: 1, title: 'Should I Stay or Should I Go', artist: 'The Clash', ano: '1982', versao: 'Rock Band I' },
      { number: 2, title: 'In Bloom', artist: 'Nirvana', ano: '1991', versao: 'Rock Band I' },
      { number: 3, title: 'Maps', artist: 'Yeah Yeah Yeahs', ano: '2003', versao: 'Rock Band I' },
      { number: 4, title: 'Mississippi Queen', artist: 'Mountain', ano: '1970', versao: 'Rock Band I' },
      { number: 5, title: 'Here It Goes Again', artist: 'OK Go', ano: '2005', versao: 'Rock Band I' },
      { number: 6, title: 'Blitzkrieg Bop', artist: 'Ramones', ano: '1976', versao: 'Rock Band I' },
      { number: 7, title: 'Wave of Mutilation', artist: 'Pixies', ano: '1989', versao: 'Rock Band I' },
      { number: 8, title: 'I Think I\'m Paranoid', artist: 'Garbage', ano: '1998', versao: 'Rock Band I' },
      { number: 9, title: 'Orange Crush', artist: 'R.E.M.', ano: '1988', versao: 'Rock Band I' },
      { number: 10, title: 'The Hand That Feeds', artist: 'Nine Inch Nails', ano: '2005', versao: 'Rock Band I' },
      { number: 11, title: 'Sabotage', artist: 'Beastie Boys', ano: '1994', versao: 'Rock Band I' },
      { number: 12, title: 'Say It Ain’t So', artist: 'Weezer', ano: '1994', versao: 'Rock Band I' },
      { number: 13, title: 'Learn to Fly', artist: 'Foo Fighters', ano: '1999', versao: 'Rock Band I' },
      { number: 14, title: 'Go With the Flow', artist: 'Queens of the Stone Age', ano: '2002', versao: 'Rock Band I' },
      { number: 15, title: 'Detroit Rock City', artist: 'Kiss', ano: '1976', versao: 'Rock Band I' },
      { number: 16, title: 'Creep', artist: 'Radiohead', ano: '1993', versao: 'Rock Band I' },
      { number: 17, title: 'When You Were Young', artist: 'The Killers', ano: '2006', versao: 'Rock Band I' },
      { number: 18, title: 'Celebrity Skin', artist: 'Hole', ano: '1998', versao: 'Rock Band I' },
      { number: 19, title: 'Electric Version', artist: 'The New Pornographers', ano: '2003', versao: 'Rock Band I' },
      { number: 20, title: 'Gimme Shelter', artist: 'The Rolling Stones', ano: '1969', versao: 'Rock Band I' },
      { number: 21, title: 'Suffragette City', artist: 'David Bowie', ano: '1972', versao: 'Rock Band I' },
      { number: 22, title: 'Black Hole Sun', artist: 'Soundgarden', ano: '1994', versao: 'Rock Band I' },
      { number: 23, title: 'Main Offender', artist: 'The Hives', ano: '2000', versao: 'Rock Band I' },
      { number: 24, title: 'Reptilia', artist: 'The Strokes', ano: '2003', versao: 'Rock Band I' },
      { number: 25, title: 'Epic', artist: 'Faith No More', ano: '1989', versao: 'Rock Band I' },
      { number: 26, title: 'Are You Gonna Be My Girl', artist: 'Jet', ano: '2003', versao: 'Rock Band I' },
      { number: 27, title: 'Dani California', artist: 'Red Hot Chili Peppers', ano: '2006', versao: 'Rock Band I' },
      { number: 28, title: '(Don\'t Fear) The Reaper', artist: 'Blue Oyster Cult', ano: '1976', versao: 'Rock Band I' },
      { number: 29, title: 'Paranoid', artist: 'Black Sabbath', ano: '1970', versao: 'Rock Band I' },
      { number: 30, title: 'Wanted Dead Or Alive', artist: 'Bon Jovi', ano: '1986', versao: 'Rock Band I' },
      { number: 31, title: 'Ballroom Blitz', artist: 'Sweet', ano: '1974', versao: 'Rock Band I' },
      { number: 32, title: 'Dead On Arrival', artist: 'Fall Out Boy', ano: '2003', versao: 'Rock Band I' },
      { number: 33, title: 'Vasoline', artist: 'Stone Temple Pilots', ano: '1994', versao: 'Rock Band I' },
      { number: 34, title: 'Next To You', artist: 'The Police', ano: '1978', versao: 'Rock Band I' },
      { number: 35, title: 'Won\'t Get Fooled Again', artist: 'The Who', ano: '1971', versao: 'Rock Band I' },
      { number: 36, title: 'Tom Sawyer', artist: 'Rush', ano: '1981', versao: 'Rock Band I' },
      { number: 37, title: 'Foreplay/Long Time', artist: 'Boston', ano: '1976', versao: 'Rock Band I' },
      { number: 38, title: 'Cherub Rock', artist: 'Smashing Pumpkins', ano: '1993', versao: 'Rock Band I' },
      { number: 39, title: 'Enter Sandman', artist: 'Metallica', ano: '1991', versao: 'Rock Band I' },
      { number: 40, title: 'Welcome Home', artist: 'Coheed & Cambria', ano: '2005', versao: 'Rock Band I' },
      { number: 41, title: 'Highway Star', artist: 'Deep Purple', ano: '1972', versao: 'Rock Band I' },
      { number: 42, title: 'Flirtin\' With Disaster', artist: 'Molly Hatchet', ano: '1979', versao: 'Rock Band I' },
      { number: 43, title: 'Train Kept A Rollin\'', artist: 'Aerosmith', ano: '1974', versao: 'Rock Band I' },
      { number: 44, title: 'Run To The Hills', artist: 'Iron Maiden', ano: '1982', versao: 'Rock Band I' },
      { number: 45, title: 'Green Grass & High Tides', artist: 'The Outlaws', ano: '1975', versao: 'Rock Band I' },
      { number: 46, title: 'Time We Had', artist: 'The Mother Hips', ano: '2007', versao: 'Rock Band I' },
      { number: 47, title: 'Day Late, Dollar Short', artist: 'The Acro-Brats', ano: '2006', versao: 'Rock Band I' },
      { number: 48, title: 'Seven', artist: 'Vagiant', ano: '2007', versao: 'Rock Band I' },
      { number: 49, title: '29 Fingers', artist: 'The Konks', ano: '2005', versao: 'Rock Band I' },
      { number: 50, title: 'I\'m So Sick', artist: 'Flyleaf', ano: '2005', versao: 'Rock Band I' },
      { number: 51, title: 'Blood Doll', artist: 'Anarchy Club', ano: '2007', versao: 'Rock Band I' },
      { number: 52, title: 'Nightmare', artist: 'Crooked X', ano: '2007', versao: 'Rock Band I' },
      { number: 53, title: 'I Get By', artist: 'Honest Bob & The Factory-to-dealer Incentives', ano: '2004', versao: 'Rock Band I' },
      { number: 54, title: 'Outside', artist: 'Tribe', ano: '1990', versao: 'Rock Band I' },
      { number: 55, title: 'Brainpower', artist: 'Freezepop', ano: '2007', versao: 'Rock Band I' },
      { number: 56, title: 'Can\'t Let Go', artist: 'Death Of The Cool', ano: '2007', versao: 'Rock Band I' },
      { number: 57, title: 'Timmy & The Lords Of The Underworld', artist: 'Timmy & The Lords Of The Underworld', ano: '2000', versao: 'Rock Band I' },
      { number: 58, title: 'Pleasure (Pleasure)', artist: 'Bang Camaro', ano: '2007', versao: 'Rock Band I' },
      { number: 59, title: 'Roxanne', artist: 'The Police', ano: '1978', versao: 'Rock Band I' },
      { number: 60, title: 'Dirty Little Secrets', artist: 'The All-American Rejects', ano: '2005', versao: 'Rock Band I' },
      { number: 61, title: 'Rockaway Beach', artist: 'Ramones', ano: '1977', versao: 'Rock Band I' },
      { number: 62, title: 'Roam', artist: 'The B-52s', ano: '1989', versao: 'Rock Band I' },
      { number: 63, title: 'Don\'t Look Back In Anger', artist: 'Oasis', ano: '1995', versao: 'Rock Band I' },
      { number: 64, title: 'Beetlebum', artist: 'Blur', ano: '1997', versao: 'Rock Band I' },
      { number: 65, title: 'Monsoon', artist: 'Tokio Hotel', ano: '2007', versao: 'Rock Band I' },
      { number: 66, title: 'Countdown To Insanity', artist: 'H-Blockx', ano: '2007', versao: 'Rock Band I' },
      { number: 67, title: 'Manu Chao', artist: 'Les Wampas', ano: '2003', versao: 'Rock Band I' },
      { number: 68, title: 'Perfekte Welle', artist: 'Juli', ano: '2004', versao: 'Rock Band I' },
      { number: 69, title: 'New Wave', artist: 'Pleymo', ano: '2002', versao: 'Rock Band I' },
      { number: 70, title: 'Rock \'N\' Roll Star', artist: 'Oasis', ano: '1994', versao: 'Rock Band I' },
      { number: 71, title: 'Hysteria', artist: 'Muse', ano: '2003', versao: 'Rock Band I' },
      { number: 72, title: 'Hier Kommt Alex', artist: 'Die Toten Hosen', ano: '1988', versao: 'Rock Band I' }
    ]
  },
    {
    id: '5',
    title: 'Rock Band II',
    coverImage: "./images/rockbandii.png",
    platform: 'PlayStation 2',
    releaseDate: '2008-09-14',
    description: '',
    tracks: [
      { number: 1, title: 'Eye Of The Tiger', artist: 'Survivor', ano: '1982', versao: 'Rock Band II' },
      { number: 2, title: 'Float On', artist: 'Modest Mouse', ano: '2004', versao: 'Rock Band II' },
      { number: 3, title: 'Today', artist: 'Smashing Pumpkins', ano: '1993', versao: 'Rock Band II' },
      { number: 4, title: 'Hungry Like A Wolf', artist: 'Duran Duran', ano: '1982', versao: 'Rock Band II' },
      { number: 5, title: 'Cool For Cats', artist: 'Squeeze', ano: '1979', versao: 'Rock Band II' },
      { number: 6, title: 'Pretend We\'Re Dead', artist: 'L7', ano: '1992', versao: 'Rock Band II' },
      { number: 7, title: 'My Own Worst Enemy', artist: 'Lit', ano: '1999', versao: 'Rock Band II' },
      { number: 8, title: 'One Step Closer', artist: 'Linkin Park', ano: '2000', versao: 'Rock Band II' },
      { number: 9, title: 'We Got The Beat', artist: 'The Go-Go\'S', ano: '1981', versao: 'Rock Band II' },
      { number: 10, title: 'That\'S What You Get', artist: 'Paramore', ano: '2007', versao: 'Rock Band II' },
      { number: 11, title: 'Rebel Girl', artist: 'Bikini Kill', ano: '1993', versao: 'Rock Band II' },
      { number: 12, title: 'So What\'Cha Want', artist: 'Beastie Boys', ano: '1992', versao: 'Rock Band II' },
      { number: 13, title: 'Drain You', artist: 'Nirvana', ano: '1991', versao: 'Rock Band II' },
      { number: 14, title: 'New Kid In School', artist: 'The Donnas', ano: '2007', versao: 'Rock Band II' },
      { number: 15, title: 'Hello There', artist: 'Cheap Trick', ano: '1977', versao: 'Rock Band II' },
      { number: 16, title: 'Lump', artist: 'Presidents Of The United States Of America', ano: '1995', versao: 'Rock Band II' },
      { number: 17, title: 'American Woman', artist: 'The Guess Who', ano: '1970', versao: 'Rock Band II' },
      { number: 18, title: 'I Was Wrong', artist: 'Social Distortion', ano: '1996', versao: 'Rock Band II' },
      { number: 19, title: 'Nine In The Afternoon', artist: 'Panic! At The Disco', ano: '2008', versao: 'Rock Band II' },
      { number: 20, title: 'Mountain Song', artist: 'Jane\'S Addiction', ano: '1988', versao: 'Rock Band II' },
      { number: 21, title: 'Man In The Box', artist: 'Alice In Chains', ano: '1991', versao: 'Rock Band II' },
      { number: 22, title: 'Our Truth', artist: 'Lacuna Coil', ano: '2006', versao: 'Rock Band II' },
      { number: 23, title: 'White Wedding (Part 1)', artist: 'Billy Idol', ano: '1982', versao: 'Rock Band II' },
      { number: 24, title: 'E-Pro', artist: 'Beck', ano: '2005', versao: 'Rock Band II' },
      { number: 25, title: 'Psycho Killer', artist: 'Talking Heads', ano: '1977', versao: 'Rock Band II' },
      { number: 26, title: 'Spirit In The Sky', artist: 'Norman Greenbaum', ano: '1969', versao: 'Rock Band II' },
      { number: 27, title: 'Kids In America', artist: 'The Muffs', ano: '1995', versao: 'Rock Band II' },
      { number: 28, title: 'Feel The Pain', artist: 'Dinosaur Jr.', ano: '1994', versao: 'Rock Band II' },
      { number: 29, title: 'Give It Away', artist: 'Red Hot Chili Peppers', ano: '1991', versao: 'Rock Band II' },
      { number: 30, title: 'Conventional Lover', artist: 'Speck', ano: '2007', versao: 'Rock Band II' },
      { number: 31, title: 'A Jagged Gorgeous Winter', artist: 'The Main Drag', ano: '2008', versao: 'Rock Band II' },
      { number: 32, title: 'Bad Reputation', artist: 'Joan Jett', ano: '1980', versao: 'Rock Band II' },
      { number: 33, title: 'Pump It Up', artist: 'Elvis Costello', ano: '1978', versao: 'Rock Band II' },
      { number: 34, title: 'You Outta Know', artist: 'Alanis Morissette', ano: '1995', versao: 'Rock Band II' },
      { number: 35, title: 'Go Your Own Way', artist: 'Fleetwood Mac', ano: '1977', versao: 'Rock Band II' },
      { number: 36, title: 'Welcome To The Neighborhood', artist: 'The Libyans', ano: '2008', versao: 'Rock Band II' },
      { number: 37, title: 'Pda', artist: 'Interpol', ano: '2002', versao: 'Rock Band II' },
      { number: 38, title: 'Shooting Star', artist: 'Bad Company', ano: '1975', versao: 'Rock Band II' },
      { number: 39, title: 'Livin\' On A Prayer', artist: 'Bon Jovi', ano: '1986', versao: 'Rock Band II' },
      { number: 40, title: 'De-Luxe', artist: 'Lush', ano: '1990', versao: 'Rock Band II' },
      { number: 41, title: 'Girls Not Grey', artist: 'Afi', ano: '2003', versao: 'Rock Band II' },
      { number: 42, title: 'One Way Or Another', artist: 'Blondie', ano: '1978', versao: 'Rock Band II' },
      { number: 43, title: 'Tangled Up In Blue', artist: 'Bob Dylan', ano: '1975', versao: 'Rock Band II' },
      { number: 44, title: 'Alex Chilton', artist: 'The Replacements', ano: '1987', versao: 'Rock Band II' },
      { number: 45, title: 'Alive', artist: 'Pearl Jam', ano: '1991', versao: 'Rock Band II' },
      { number: 46, title: 'The Middle', artist: 'Jimmy Eat World', ano: '2001', versao: 'Rock Band II' },
      { number: 47, title: 'Aqualung', artist: 'Jethro Tull', ano: '1971', versao: 'Rock Band II' },
      { number: 48, title: 'Supreme Girl', artist: 'The Sterns', ano: '2006', versao: 'Rock Band II' },
      { number: 49, title: 'Down With The Sickness', artist: 'Disturbed', ano: '2000', versao: 'Rock Band II' },
      { number: 50, title: 'Give It All', artist: 'Rise Against', ano: '2004', versao: 'Rock Band II' },
      { number: 51, title: 'Where\'D You Go', artist: 'The Mighty Mighty Bosstones', ano: '1991', versao: 'Rock Band II' },
      { number: 52, title: 'Come Out And Play (Keep \'Em Separated)', artist: 'The Offspring', ano: '1994', versao: 'Rock Band II' },
      { number: 53, title: 'Everlong', artist: 'Foo Fighters', ano: '1997', versao: 'Rock Band II' },
      { number: 54, title: 'Pinball Wizard', artist: 'The Who', ano: '1969', versao: 'Rock Band II' },
      { number: 55, title: 'Rob The Prez-O-Dent', artist: 'That Handsome Devil', ano: '2008', versao: 'Rock Band II' },
      { number: 56, title: 'Testify', artist: 'Rage Against The Machine', ano: '1999', versao: 'Rock Band II' },
      { number: 57, title: 'Uncontrollable Urge', artist: 'Devo', ano: '1978', versao: 'Rock Band II' },
      { number: 58, title: 'Any Way You Want It', artist: 'Journey', ano: '1980', versao: 'Rock Band II' },
      { number: 59, title: 'Round And Round', artist: 'Ratt', ano: '1984', versao: 'Rock Band II' },
      { number: 60, title: 'Night Lies', artist: 'Bang Camaro', ano: '2008', versao: 'Rock Band II' },
      { number: 61, title: 'Let There Be Rock', artist: 'Ac/Dc', ano: '1977', versao: 'Rock Band II' },
      { number: 62, title: 'Alabama Getaway', artist: 'Grateful Dead', ano: '1980', versao: 'Rock Band II' },
      { number: 63, title: 'Lazy Eye', artist: 'Silversun Pickups', ano: '2006', versao: 'Rock Band II' },
      { number: 64, title: 'Teen Age Riot', artist: 'Sonic Youth', ano: '1988', versao: 'Rock Band II' },
      { number: 65, title: 'The Trees (Vault Edition)', artist: 'Rush', ano: '1978', versao: 'Rock Band II' },
      { number: 66, title: 'Carry On Wayward Son', artist: 'Kansas', ano: '1976', versao: 'Rock Band II' },
      { number: 67, title: 'Rock\'N Me', artist: 'Steve Miller Band', ano: '1976', versao: 'Rock Band II' },
      { number: 68, title: 'Ace Of Spades \'08', artist: 'Motorhead', ano: '2008', versao: 'Rock Band II' },
      { number: 69, title: 'Spoonman', artist: 'Soundgarden', ano: '1994', versao: 'Rock Band II' },
      { number: 70, title: 'Almost Easy', artist: 'Avenged Sevenfold', ano: '2007', versao: 'Rock Band II' },
      { number: 71, title: 'Chop Suey', artist: 'System Of A Down', ano: '2001', versao: 'Rock Band II' },
      { number: 72, title: 'Shackler\'S Revenge', artist: 'Guns N\' Roses', ano: '2008', versao: 'Rock Band II' },
      { number: 73, title: 'Master Exploder', artist: 'Tenacious D', ano: '2006', versao: 'Rock Band II' },
      { number: 74, title: 'Ramblin\' Man', artist: 'The Allman Brothers Band', ano: '1973', versao: 'Rock Band II' },
      { number: 75, title: 'Shoulder To The Plow', artist: 'Breaking Wheel', ano: '2008', versao: 'Rock Band II' },
      { number: 76, title: 'Get Clean', artist: 'Anarchy Club', ano: '2009', versao: 'Rock Band II' },
      { number: 77, title: 'Colony Of Birchmen', artist: 'Mastodon', ano: '2006', versao: 'Rock Band II' },
      { number: 78, title: 'Peace Sells', artist: 'Megadeth', ano: '1986', versao: 'Rock Band II' },
      { number: 79, title: 'Souls Of Black', artist: 'Testament', ano: '1990', versao: 'Rock Band II' },
      { number: 80, title: 'Bodhisattva', artist: 'Steely Dan', ano: '1973', versao: 'Rock Band II' },
      { number: 81, title: 'Battery', artist: 'Metallica', ano: '1986', versao: 'Rock Band II' },
      { number: 82, title: 'Panic Attack', artist: 'Dream Theater', ano: '2005', versao: 'Rock Band II' },
      { number: 83, title: 'Visions', artist: 'Abnormality', ano: '2007', versao: 'Rock Band II' },
      { number: 84, title: 'Painkiller', artist: 'Judas Priest', ano: '1990', versao: 'Rock Band II' }
    ]
  }
];